In [1]:
import pandas as pd
import numpy as np

In [2]:
upward_df = pd.read_csv("Data/upward.csv")

In [3]:
upward_df.loc[upward_df['tic'] == 'STOCK']

,date,tic,close,return_t-1,return_t-2,return_t-3,ma_3,ma_5,ma_10,log_return,volatility_5,momentum_5
991,2023-01-10,STOCK,109,0.009259,0.018692,0.028302,108.0,107.0,104.5,0.009217,0.000139,5.0
992,2023-01-11,STOCK,110,0.009174,0.018519,0.028037,109.0,108.0,105.5,0.009132,0.000137,5.0
993,2023-01-12,STOCK,111,0.009091,0.018349,0.027778,110.0,109.0,106.5,0.009050,0.000134,5.0
994,2023-01-13,STOCK,112,0.009009,0.018182,0.027523,111.0,110.0,107.5,0.008969,0.000132,5.0
995,2023-01-14,STOCK,113,0.008929,0.018018,0.027273,112.0,111.0,108.5,0.008889,0.000130,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1977,2025-09-22,STOCK,1095,0.000914,0.001830,0.002747,1094.0,1093.0,1090.5,0.000914,0.000001,5.0
1978,2025-09-23,STOCK,1096,0.000913,0.001828,0.002745,1095.0,1094.0,1091.5,0.000913,0.000001,5.0
1979,2025-09-24,STOCK,1097,0.000912,0.001826,0.002742,1096.0,1095.0,1092.5,0.000912,0.000001,5.0
1980,2025-09-25,STOCK,1098,0.000912,0.001825,0.002740,1097.0,1096.0,1093.5,0.000911,0.000001,5.0
1981,2025-09-26,STOCK,1099,0.000911,0.001823,0.002737,1098.0,1097.0,1094.5,0.000910,0.000001,5.0

giorno 0:  weights 50% 50% (converted to 1,0), stock value (10/01/23): 109,  portfolio value = 1000
+ step di 1
giorno 1: weights 50% 50%,(1,0) stock value (11/01/23): 110,  portfolio value = 1000
+ step di 1
giorno 2: weights (0,1), stock value (12/01/23): 111, portfolio_value = 1,009.09

ma siccome il day 1 è sempre fisso per via dell'inizializzazione forzata, devo iniziare da il day 2 fino al giorno 990

In [4]:
C = 1000
weight = 1
R = 1099/110

v = C * (weight * R + (1-weight)* 1)
v

9990.90909090909

In [5]:
upward_run_work = pd.read_csv("Results/250619_hc_binary_udp/ddpg/upward/training_logs/01.csv")

In [6]:
optimal_upward_df_binary = upward_run_work.loc[(upward_run_work['episode'] == 50), ['day', 'allocation_weights', 'new_portfolio_value']]

In [7]:
optimal_upward_df_binary

       day allocation_weights new_portfolio_value
48510    1         1.00, 0.00            1,000.00
48511    2         0.00, 1.00            1,009.09
48512    3         0.00, 1.00            1,018.18
48513    4         0.00, 1.00            1,027.27
48514    5         0.00, 1.00            1,036.36
...    ...                ...                 ...
49495  986         0.00, 1.00            9,954.55
49496  987         0.00, 1.00            9,963.64
49497  988         0.00, 1.00            9,972.73
49498  989         0.00, 1.00            9,981.82
49499  990         0.00, 1.00            9,990.91

[990 rows x 3 columns]

In [8]:
len(optimal_upward_df_binary)

990

In [9]:
C = 1000
weight = 0
R = 1/991

v = C * (weight * R + (1-weight)* 1)
v

1000.0

In [10]:
optimal_downward_df_binary = upward_run_work.loc[(upward_run_work['episode'] == 50), ['day', 'allocation_weights', 'new_portfolio_value']]
optimal_downward_df_binary['new_portfolio_value'] = 1000
optimal_downward_df_binary["allocation_weights"] = [[1, 0]] * len(optimal_downward_df_binary)
optimal_downward_df_binary

       day allocation_weights  new_portfolio_value
48510    1             [1, 0]                 1000
48511    2             [1, 0]                 1000
48512    3             [1, 0]                 1000
48513    4             [1, 0]                 1000
48514    5             [1, 0]                 1000
...    ...                ...                  ...
49495  986             [1, 0]                 1000
49496  987             [1, 0]                 1000
49497  988             [1, 0]                 1000
49498  989             [1, 0]                 1000
49499  990             [1, 0]                 1000

[990 rows x 3 columns]

In [11]:
periodic_df = pd.read_csv("Data/periodic.csv")

In [12]:
periodic_df.loc[periodic_df['tic'] =='STOCK'].iloc[:5]

,date,tic,close,return_t-1,return_t-2,return_t-3,ma_3,ma_5,ma_10,log_return,volatility_5,momentum_5
991,2023-01-10,STOCK,546.601954,0.005946,0.013791,0.023442,543.046487,538.290705,523.544972,0.005928,0.002549,24.853678
992,2023-01-11,STOCK,548.786168,0.003996,0.009966,0.017842,546.253094,542.401513,528.423588,0.003988,0.002785,20.554044
993,2023-01-12,STOCK,549.874749,0.001984,0.005988,0.011969,548.420957,545.560076,533.411063,0.001982,0.002969,15.792811
994,2023-01-13,STOCK,549.843251,-0.000057,0.001926,0.005930,549.501390,547.695457,537.648198,-0.000057,0.003099,10.676906
995,2023-01-14,STOCK,548.692382,-0.002093,-0.002150,-0.000171,549.470127,548.759701,541.039835,-0.002095,0.003177,5.321220

In [13]:
class PeriodicTrendPriceGenerator:
    def __init__(self, start=500, amplitude=50, frequency=0.15):
        self.start = start
        self.amplitude = amplitude
        self.frequency = frequency
        self.t = 0

    def generate_price(self, last_price=None):
        value = self.amplitude * np.sin(self.frequency * self.t) + self.start
        self.t += 1
        return value

# Generate 991 days of stock prices
days = 999
generator = PeriodicTrendPriceGenerator(start= 500, amplitude=50, frequency=0.15)
stock_prices = [generator.generate_price() for _ in range(days)]

stock_prices = np.array(stock_prices)[8:]
allocation = [1,0]
portfolio_value = 1000
days_df = []
optimal_allocations = []
optimal_portfolio_values = []

for day, stock_price in enumerate(stock_prices):
    print("day: ", day)
    if day == 0:
       pass
    else:
        if day == 1:
           
            assert round(stock_prices[day]) == 549
        old_allocation = allocation
        
        print("stock price today", stock_prices[day])
        print("stock price yesterday", stock_prices[day-1])
        portfolio_return = sum((np.array([500, stock_prices[day]]) / np.array([500, stock_prices[day-1]])-1)*np.array(old_allocation))
        new_portfolio_value = portfolio_value*(1+portfolio_return)
        portfolio_value = new_portfolio_value
        print("portfolio_value", portfolio_value)
        if (stock_prices[day] > stock_prices[day-1]):
            allocation = [0, 1]
        else:
            allocation = [1, 0]
        print("old_allocation", old_allocation)
        print("allocation:", allocation)
        days_df.append(day)
        optimal_allocations.append(old_allocation)
        optimal_portfolio_values.append(portfolio_value)

optimal_periodic_df_binary = pd.DataFrame({"day": days_df,
                                            "allocation_weights":optimal_allocations,
                                            "new_portfolio_value": optimal_portfolio_values
                                           })

day:  0
day:  1
stock price today 548.786167891333
stock price yesterday 546.6019542983613
portfolio_value 1000.0
old_allocation [1, 0]
allocation: [0, 1]
day:  2
stock price today 549.8747493302027
stock price yesterday 548.786167891333
portfolio_value 1001.9836167574204
old_allocation [0, 1]
allocation: [0, 1]
day:  3
stock price today 549.843251422696
stock price yesterday 549.8747493302027
portfolio_value 1001.9262211644743
old_allocation [0, 1]
allocation: [1, 0]
day:  4
stock price today 548.6923815439097
stock price yesterday 549.843251422696
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  5
stock price today 546.4479857501934
stock price yesterday 548.6923815439097
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  6
stock price today 543.1604683324437
stock price yesterday 546.4479857501934
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  7
stock price today 538.9036598443961
stock price yesterday 543.1604683324437
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  8
stock price today 533.7731590275575
stock price yesterday 538.9036598443961
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  9
stock price today 527.8841858695708
stock price yesterday 533.7731590275575
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  10
stock price today 521.3689940116915
stock price yesterday 527.8841858695708
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  11
stock price today 514.3739006171272
stock price yesterday 521.3689940116915
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  12
stock price today 507.05600040299333
stock price yesterday 514.3739006171272
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  13
stock price today 499.5796376316426
stock price yesterday 507.05600040299333
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  14
stock price today 492.1127152928376
stock price yesterday 499.5796376316426
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  15
stock price today 484.82292436457857
stock price yesterday 492.1127152928376
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  16
stock price today 477.8739778352574
stock price yesterday 484.82292436457857
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  17
stock price today 471.4219340628828
stock price yesterday 477.8739778352574
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  18
stock price today 465.6116920408013
stock price yesterday 471.4219340628828
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  19
stock price today 460.57373727869026
stock price yesterday 465.6116920408013
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  20
stock price today 456.4212113793206
stock price yesterday 460.57373727869026
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  21
stock price today 453.24737112207754
stock price yesterday 456.4212113793206
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  22
stock price today 451.1234941167452
stock price yesterday 453.24737112207754
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  23
stock price today 450.09727806205603
stock price yesterday 451.1234941167452
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [1, 0]
day:  24
stock price today 450.19176955820797
stock price yesterday 450.09727806205603
portfolio_value 1001.9262211644743
old_allocation [1, 0]
allocation: [0, 1]
day:  25
stock price today 451.404846529909
stock price yesterday 450.19176955820797
portfolio_value 1004.6259898151335
old_allocation [0, 1]
allocation: [0, 1]
day:  26
stock price today 453.7092658836134
stock price yesterday 451.404846529909
portfolio_value 1009.7546001788928
old_allocation [0, 1]
allocation: [0, 1]
day:  27
stock price today 457.0532753286704
stock price yesterday 453.7092658836134
portfolio_value 1017.1968747236101
old_allocation [0, 1]
allocation: [0, 1]
day:  28
stock price today 461.36177562220064
stock price yesterday 457.0532753286704
portfolio_value 1026.7856760076031
old_allocation [0, 1]
allocation: [0, 1]
day:  29
stock price today 466.5380071361869
stock price yesterday 461.36177562220064
portfolio_value 1038.305660226262
old_allocation [0, 1]
allocation: [0, 1]
day:  30
stock price today 472.4657228701181
stock price yesterday 466.5380071361869
portfolio_value 1051.4981133696485
old_allocation [0, 1]
allocation: [0, 1]
day:  31
stock price today 479.01179910800704
stock price yesterday 472.4657228701181
portfolio_value 1066.0667613814035
old_allocation [0, 1]
allocation: [0, 1]
day:  32
stock price today 486.0292250900537
stock price yesterday 479.01179910800704
portfolio_value 1081.6844238353244
old_allocation [0, 1]
allocation: [0, 1]
day:  33
stock price today 493.3604045573741
stock price yesterday 486.0292250900537
portfolio_value 1098.0003617023788
old_allocation [0, 1]
allocation: [0, 1]
day:  34
stock price today 500.8406950242175
stock price yesterday 493.3604045573741
portfolio_value 1114.6481541931475
old_allocation [0, 1]
allocation: [0, 1]
day:  35
stock price today 508.30210529324785
stock price yesterday 500.8406950242175
portfolio_value 1131.2539277787992
old_allocation [0, 1]
allocation: [0, 1]
day:  36
stock price today 515.5770681756688
stock price yesterday 508.30210529324785
portfolio_value 1147.4447525845235
old_allocation [0, 1]
allocation: [0, 1]
day:  37
stock price today 522.5022036890309
stock price yesterday 515.5770681756688
portfolio_value 1162.8570175905315
old_allocation [0, 1]
allocation: [0, 1]
day:  38
stock price today 528.92198821941
stock price yesterday 522.5022036890309
portfolio_value 1177.1445965516596
old_allocation [0, 1]
allocation: [0, 1]
day:  39
stock price today 534.6922472464881
stock price yesterday 528.92198821941
portfolio_value 1189.9866212466338
old_allocation [0, 1]
allocation: [0, 1]
day:  40
stock price today 539.6833931924576
stock price yesterday 534.6922472464881
portfolio_value 1201.0946874865676
old_allocation [0, 1]
allocation: [0, 1]
day:  41
stock price today 543.7833356796441
stock price yesterday 539.6833931924576
portfolio_value 1210.219332051282
old_allocation [0, 1]
allocation: [0, 1]
day:  42
stock price today 546.8999988387369
stock price yesterday 543.7833356796441
portfolio_value 1217.15563509542
old_allocation [0, 1]
allocation: [0, 1]
day:  43
stock price today 548.96338913431
stock price yesterday 546.8999988387369
portfolio_value 1221.7478222063921
old_allocation [0, 1]
allocation: [0, 1]
day:  44
stock price today 549.9271672687303
stock price yesterday 548.96338913431
portfolio_value 1223.8927627618543
old_allocation [0, 1]
allocation: [0, 1]
day:  45
stock price today 549.769688862881
stock price yesterday 549.9271672687303
portfolio_value 1223.5422860211481
old_allocation [0, 1]
allocation: [1, 0]
day:  46
stock price today 548.4944905422543
stock price yesterday 549.769688862881
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  47
stock price today 546.130210511967
stock price yesterday 548.4944905422543
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  48
stock price today 542.729945404414
stock price yesterday 546.130210511967
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  49
stock price today 538.3700578433744
stock price yesterday 542.729945404414
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  50
stock price today 533.1484615041092
stock price yesterday 538.3700578433744
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  51
stock price today 527.1824221833044
stock price yesterday 533.1484615041092
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  52
stock price today 520.6059242620878
stock price yesterday 527.1824221833044
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  53
stock price today 513.5666617056817
stock price yesterday 520.6059242620878
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  54
stock price today 506.2227211753532
stock price yesterday 513.5666617056817
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  55
stock price today 498.7390317428171
stock price yesterday 506.2227211753532
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  56
stock price today 491.283660938851
stock price yesterday 498.7390317428171
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  57
stock price today 484.0240403188863
stock price yesterday 491.283660938851
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  58
stock price today 477.12320531123396
stock price yesterday 484.0240403188863
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  59
stock price today 470.73613379284825
stock price yesterday 477.12320531123396
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  60
stock price today 465.0062656203229
stock price yesterday 470.73613379284825
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  61
stock price today 460.06228127994996
stock price yesterday 465.0062656203229
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  62
stock price today 456.0152120014165
stock price yesterday 460.06228127994996
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  63
stock price today 452.9559462357546
stock price yesterday 456.0152120014165
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  64
stock price today 450.95318849667547
stock price yesterday 452.9559462357546
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  65
stock price today 450.05191640530916
stock price yesterday 450.95318849667547
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [1, 0]
day:  66
stock price today 450.2723705898005
stock price yesterday 450.05191640530916
portfolio_value 1223.5422860211481
old_allocation [1, 0]
allocation: [0, 1]
day:  67
stock price today 451.60960012443695
stock price yesterday 450.2723705898005
portfolio_value 1227.175990837637
old_allocation [0, 1]
allocation: [0, 1]
day:  68
stock price today 454.0335737167662
stock price yesterday 451.60960012443695
portfolio_value 1233.7627467305838
old_allocation [0, 1]
allocation: [0, 1]
day:  69
stock price today 457.48985414568165
stock price yesterday 454.0335737167662
portfolio_value 1243.154629362836
old_allocation [0, 1]
allocation: [0, 1]
day:  70
stock price today 461.90082080404835
stock price yesterday 457.48985414568165
portfolio_value 1255.140717298171
old_allocation [0, 1]
allocation: [0, 1]
day:  71
stock price today 467.1674128901992
stock price yesterday 461.90082080404835
portfolio_value 1269.4518288420334
old_allocation [0, 1]
allocation: [0, 1]
day:  72
stock price today 473.17135409997826
stock price yesterday 467.1674128901992
portfolio_value 1285.766567282074
old_allocation [0, 1]
allocation: [0, 1]
day:  73
stock price today 479.777808857543
stock price yesterday 473.17135409997826
portfolio_value 1303.7185387654185
old_allocation [0, 1]
allocation: [0, 1]
day:  74
stock price today 486.83841043170986
stock price yesterday 479.777808857543
portfolio_value 1322.9045807147052
old_allocation [0, 1]
allocation: [0, 1]
day:  75
stock price today 494.1945929328771
stock price yesterday 486.83841043170986
portfolio_value 1342.8938159904058
old_allocation [0, 1]
allocation: [0, 1]
day:  76
stock price today 501.68115236105683
stock price yesterday 494.1945929328771
portfolio_value 1363.2373294624617
old_allocation [0, 1]
allocation: [0, 1]
day:  77
stock price today 509.1299567315567
stock price yesterday 501.68115236105683
portfolio_value 1383.478249676304
old_allocation [0, 1]
allocation: [0, 1]
day:  78
stock price today 516.3737219568847
stock price yesterday 509.1299567315567
portfolio_value 1403.162009200764
old_allocation [0, 1]
allocation: [0, 1]
day:  79
stock price today 523.249768686711
stock price yesterday 516.3737219568847
portfolio_value 1421.8465532325904
old_allocation [0, 1]
allocation: [0, 1]
day:  80
stock price today 529.6036757353611
stock price yesterday 523.249768686711
portfolio_value 1439.112267194315
old_allocation [0, 1]
allocation: [0, 1]
day:  81
stock price today 535.2927480487332
stock price yesterday 529.6036757353611
portfolio_value 1454.5714003730288
old_allocation [0, 1]
allocation: [0, 1]
day:  82
stock price today 540.1892213275811
stock price yesterday 535.2927480487332
portfolio_value 1467.8767739654513
old_allocation [0, 1]
allocation: [0, 1]
day:  83
stock price today 544.1831313382318
stock price yesterday 540.1892213275811
portfolio_value 1478.7295779653798
old_allocation [0, 1]
allocation: [0, 1]
day:  84
stock price today 547.1847834722053
stock price yesterday 544.1831313382318
portfolio_value 1486.8860817922337
old_allocation [0, 1]
allocation: [0, 1]
day:  85
stock price today 549.1267670937505
stock price yesterday 547.1847834722053
portfolio_value 1492.16310795444
old_allocation [0, 1]
allocation: [0, 1]
day:  86
stock price today 549.9654694373959
stock price yesterday 549.1267670937505
portfolio_value 1494.4421458209897
old_allocation [0, 1]
allocation: [0, 1]
day:  87
stock price today 549.6820550566381
stock price yesterday 549.9654694373959
portfolio_value 1493.6720131147135
old_allocation [0, 1]
allocation: [1, 0]
day:  88
stock price today 548.2828888274639
stock price yesterday 549.6820550566381
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  89
stock price today 545.799393006957
stock price yesterday 548.2828888274639
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  90
stock price today 542.2873415571468
stock price yesterday 545.799393006957
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  91
stock price today 537.825607582062
stock price yesterday 542.2873415571468
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  92
stock price today 532.5143920078558
stock price yesterday 537.825607582062
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  93
stock price today 526.4729732860233
stock price yesterday 532.5143920078558
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  94
stock price today 519.8370286565307
stock price yesterday 526.4729732860233
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  95
stock price today 512.7555871295087
stock price yesterday 519.8370286565307
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  96
stock price today 505.3876826149722
stock price yesterday 512.7555871295087
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  97
stock price today 497.898782364058
stock price yesterday 505.3876826149722
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  98
stock price today 490.4570709312906
stock price yesterday 497.898782364058
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  99
stock price today 483.2296731120719
stock price yesterday 490.4570709312906
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  100
stock price today 476.3789006800767
stock price yesterday 483.2296731120719
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  101
stock price today 470.0586072147383
stock price yesterday 476.3789006800767
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  102
stock price today 464.4107328815438
stock price yesterday 470.0586072147383
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  103
stock price today 459.56211676192254
stock price yesterday 464.4107328815438
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  104
stock price today 455.62164832092475
stock price yesterday 459.56211676192254
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  105
stock price today 452.67782198458957
stock price yesterday 455.62164832092475
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  106
stock price today 450.79674974591785
stock price yesterday 452.67782198458957
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  107
stock price today 450.0206764320391
stock price yesterday 450.79674974591785
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [1, 0]
day:  108
stock price today 450.36703097646836
stock price yesterday 450.0206764320391
portfolio_value 1493.6720131147135
old_allocation [1, 0]
allocation: [0, 1]
day:  109
stock price today 451.8280350028337
stock price yesterday 450.36703097646836
portfolio_value 1498.5175294938729
old_allocation [0, 1]
allocation: [0, 1]
day:  110
stock price today 454.3708775104408
stock price yesterday 451.8280350028337
portfolio_value 1506.9510346710526
old_allocation [0, 1]
allocation: [0, 1]
day:  111
stock price today 457.9384517386119
stock price yesterday 454.3708775104408
portfolio_value 1518.7831303015316
old_allocation [0, 1]
allocation: [0, 1]
day:  112
stock price today 462.4506376614162
stock price yesterday 457.9384517386119
portfolio_value 1533.7480930259346
old_allocation [0, 1]
allocation: [0, 1]
day:  113
stock price today 467.8061013107229
stock price yesterday 462.4506376614162
portfolio_value 1551.5098420440165
old_allocation [0, 1]
allocation: [0, 1]
day:  114
stock price today 473.8845705186634
stock price yesterday 467.8061013107229
portfolio_value 1571.66948676489
old_allocation [0, 1]
allocation: [0, 1]
day:  115
stock price today 480.5495359712292
stock price yesterday 473.8845705186634
portfolio_value 1593.7742850297395
old_allocation [0, 1]
allocation: [0, 1]
day:  116
stock price today 487.6513169131688
stock price yesterday 480.5495359712292
portfolio_value 1617.327810724654
old_allocation [0, 1]
allocation: [0, 1]
day:  117
stock price today 495.0304226550576
stock price yesterday 487.6513169131688
portfolio_value 1641.8011024409147
old_allocation [0, 1]
allocation: [0, 1]
day:  118
stock price today 502.52113439034053
stock price yesterday 495.0304226550576
portfolio_value 1666.64454280786
old_allocation [0, 1]
allocation: [0, 1]
day:  119
stock price today 509.9552268824599
stock price yesterday 502.52113439034053
portfolio_value 1691.300201714129
old_allocation [0, 1]
allocation: [0, 1]
day:  120
stock price today 517.1657464409948
stock price yesterday 509.9552268824599
portfolio_value 1715.2143662151325
old_allocation [0, 1]
allocation: [0, 1]
day:  121
stock price today 523.9907603416184
stock price yesterday 517.1657464409948
portfolio_value 1737.8499757320578
old_allocation [0, 1]
allocation: [0, 1]
day:  122
stock price today 530.27699348598
stock price yesterday 523.9907603416184
portfolio_value 1758.698683274635
old_allocation [0, 1]
allocation: [0, 1]
day:  123
stock price today 535.8832706299714
stock price yesterday 530.27699348598
portfolio_value 1777.2922718186023
old_allocation [0, 1]
allocation: [0, 1]
day:  124
stock price today 540.6836868753553
stock price yesterday 535.8832706299714
portfolio_value 1793.2131694506622
old_allocation [0, 1]
allocation: [0, 1]
day:  125

In [14]:
optimal_periodic_df_binary

     day allocation_weights  new_portfolio_value
0      1             [1, 0]          1000.000000
1      2             [0, 1]          1001.983617
2      3             [0, 1]          1001.926221
3      4             [1, 0]          1001.926221
4      5             [1, 0]          1001.926221
..   ...                ...                  ...
985  986             [1, 0]         95929.842356
986  987             [1, 0]         95929.842356
987  988             [1, 0]         95929.842356
988  989             [0, 1]         96323.358112
989  990             [0, 1]         96943.386178

[990 rows x 3 columns]

In [15]:
upward_exp_4 = pd.read_csv("Data/optimal_portfolio_values_calculations/upward_exp_4.csv")

In [16]:
upward_exp_4.loc[upward_exp_4['tic'] == 'STOCK'].iloc[:991]

            date    tic  close
1000  2023-01-01  STOCK    100
1001  2023-01-02  STOCK    101
1002  2023-01-03  STOCK    102
1003  2023-01-04  STOCK    103
1004  2023-01-05  STOCK    104
...          ...    ...    ...
1986  2025-09-13  STOCK   1086
1987  2025-09-14  STOCK   1087
1988  2025-09-15  STOCK   1088
1989  2025-09-16  STOCK   1089
1990  2025-09-17  STOCK   1090

[991 rows x 3 columns]

In [17]:
C = 1005
weight = 1
R = 1090/101
v = C * (weight * R + (1-weight)* 1)
v

10846.039603960397

In [18]:
upward_run_work_exp_4 = pd.read_csv("Data/optimal_portfolio_values_calculations/run_worked_upward_exp_4.csv")

In [19]:
upward_run_work_exp_4.loc[(upward_run_work_exp_4['episode'] == 500)].iloc[:990]

,episode,day,actions,allocation_weights,portfolio_return,reward,new_portfolio_value
498501,500,1,"0.50, 0.50","0.50, 0.50",0.50%,1005.00,"1,005"
498502,500,2,"0.00, 1.00","0.00, 1.00",0.99%,1014.95,"1,015"
498503,500,3,"0.00, 1.00","0.00, 1.00",0.98%,1024.90,"1,025"
498504,500,4,"0.00, 1.00","0.00, 1.00",0.97%,1034.85,"1,035"
498505,500,5,"0.00, 1.00","0.00, 1.00",0.96%,1044.80,"1,045"
...,...,...,...,...,...,...,...
499486,500,986,"0.00, 1.00","0.00, 1.00",0.09%,10806.24,"10,806"
499487,500,987,"0.00, 1.00","0.00, 1.00",0.09%,10816.19,"10,816"
499488,500,988,"0.00, 1.00","0.00, 1.00",0.09%,10826.14,"10,826"
499489,500,989,"0.00, 1.00","0.00, 1.00",0.09%,10836.09,"10,836"
499490,500,990,"0.00, 1.00","0.00, 1.00",0.09%,10846.04,"10,846"

In [20]:
optimal_upward_df_exp_4 = upward_run_work_exp_4.loc[(upward_run_work_exp_4['episode'] == 500)].iloc[:990].loc[:, ['day', 'allocation_weights', 'new_portfolio_value']]

In [21]:
downward_exp_4 = pd.read_csv("Data/optimal_portfolio_values_calculations/downward_exp_4.csv")

In [22]:
downward = pd.read_csv("Data/downward.csv")

In [23]:
downward_exp_4.loc[downward_exp_4['tic'] == 'STOCK'].iloc[1:992] #da 999 a 9

            date    tic  close
1001  2023-01-02  STOCK    999
1002  2023-01-03  STOCK    998
1003  2023-01-04  STOCK    997
1004  2023-01-05  STOCK    996
1005  2023-01-06  STOCK    995
...          ...    ...    ...
1987  2025-09-14  STOCK     13
1988  2025-09-15  STOCK     12
1989  2025-09-16  STOCK     11
1990  2025-09-17  STOCK     10
1991  2025-09-18  STOCK      9

[991 rows x 3 columns]

In [24]:
downward_run_work = pd.read_csv("Data/optimal_portfolio_values_calculations/run_worked_downward_exp_4.csv")

In [25]:
C = 1000
weight = 0
R = 999/9
v = C * (weight * R + (1-weight)* 1)
v

1000.0

In [26]:
optimal_downward_df_exp_4 = downward_run_work.loc[(downward_run_work['episode'] == 500)].iloc[:990]

In [27]:
periodic_exp_4_df = pd.read_csv("Data/optimal_portfolio_values_calculations/periodic_exp_4.csv")

In [28]:
periodic_exp_4_df.loc[periodic_exp_4_df['tic'] =='STOCK'].iloc[:5]

            date    tic       close
1000  2023-01-01  STOCK  500.000000
1001  2023-01-02  STOCK  500.000000
1002  2023-01-03  STOCK  507.471907
1003  2023-01-04  STOCK  514.776010
1004  2023-01-05  STOCK  521.748277

In [29]:

stock_prices

array([546.6019543 , 548.78616789, 549.87474933, 549.84325142,
       548.69238154, 546.44798575, 543.16046833, 538.90365984,
       533.77315903, 527.88418587, 521.36899401, 514.37390062,
       507.0560004 , 499.57963763, 492.11271529, 484.82292436,
       477.87397784, 471.42193406, 465.61169204, 460.57373728,
       456.42121138, 453.24737112, 451.12349412, 450.09727806,
       450.19176956, 451.40484653, 453.70926588, 457.05327533,
       461.36177562, 466.53800714, 472.46572287, 479.01179911,
       486.02922509, 493.36040456, 500.84069502, 508.30210529,
       515.57706818, 522.50220369, 528.92198822, 534.69224725,
       539.68339319, 543.78333568, 546.89999884, 548.96338913,
       549.92716727, 549.76968886, 548.49449054, 546.13021051,
       542.7299454 , 538.37005784, 533.1484615 , 527.18242218,
       520.60592426, 513.56666171, 506.22272118, 498.73903174,
       491.28366094, 484.02404032, 477.12320531, 470.73613379,
       465.00626562, 460.06228128, 456.015212  , 452.95594624,
       450.9531885 , 450.05191641, 450.27237059, 451.60960012,
       454.03357372, 457.48985415, 461.9008208 , 467.16741289,
       473.1713541 , 479.77780886, 486.83841043, 494.19459293,
       501.68115236, 509.12995673, 516.37372196, 523.24976869,
       529.60367574, 535.29274805, 540.18922133, 544.18313134,
       547.18478347, 549.12676709, 549.96546944, 549.68205506,
       548.28288883, 545.79939301, 542.28734156, 537.82560758,
       532.51439201, 526.47297329, 519.83702866, 512.75558713,
       505.38768261, 497.89878236, 490.45707093, 483.22967311,
       476.37890068, 470.05860721, 464.41073288, 459.56211676,
       455.62164832, 452.67782198, 450.79674975, 450.02067643,
       450.36703098, 451.828035  , 454.37087751, 457.93845174,
       462.45063766, 467.80610131, 473.88457052, 480.54953597,
       487.65131691, 495.03042266, 502.52113439, 509.95522688,
       517.16574644, 523.99076034, 530.27699349, 535.88327063,
       540.68368688, 544.57043522, 547.45622768, 549.27625558,
       549.98964501, 549.58037478, 548.05763623, 545.45562677,
       541.83278193, 537.27046299, 531.87112981, 525.75603976,
       519.06252458, 511.9409062 , 504.55112081, 497.05912706,
       489.63317897, 482.44004733, 475.64127438, 469.38954588,
       463.8252622 , 459.07338513, 455.24063161, 452.413077  ,
       450.65422209, 450.00356697, 450.47572396, 452.06008941,
       454.7210819 , 458.39894128, 463.01107075, 468.45389182,
       474.60517048, 481.32676226, 488.4677147 , 495.86765741,
       503.36040363, 510.77768242, 517.9529177 , 524.72496916,
       530.94175111, 536.46364803, 541.16665004, 544.94513783,
       547.71425472, 549.41181232, 549.99968714, 549.46467678,
       547.81879642, 545.09900898, 541.36639503, 536.70478103,
       531.21885677, 525.0318243 , 518.28263101, 511.12284925,
       503.71327228, 496.22030321, 488.81221799, 481.65538623,
       474.91053495, 468.72913896, 463.2500191 , 458.59622458,
       454.87226959, 452.16178614, 450.52564584, 450.00059287,
       450.5984188 , 452.30569773, 455.08408787, 458.87119257,
       463.58196161, 469.11060128, 475.33295025, 482.10926798,
       489.28737299, 496.70606049, 504.19872278, 511.59709081,
       518.73501318, 525.45218755, 531.59776065, 537.03371617,
       541.63797427, 545.30713322, 547.95879165, 549.533399  ,
       549.99559301, 549.33499377, 547.56643694, 544.72964048,
       540.88831273, 536.12872162, 530.55775731, 524.30053166,
       517.49756845, 510.30164757, 502.87437391, 495.382548  ,
       487.9944201 , 480.87591165, 474.186889  , 468.07757316,
       462.68516622, 458.13076999, 454.51666641, 451.92402044,
       450.41105733, 450.01175496, 450.73508081, 452.56479053,
       455.4597928 , 459.35507209, 464.16314884, 469.77604401,
       476.06770407, 482.8968319 , 490.11006002, 497.54539486,
       505.03585485, 512.41322039, 519.51181177, 526.17220991,
       532.24483665, 537.59331387, 542.0975263 , 545.65631906,
       548.18976931, 549.64098124, 549.97736375, 549.19136242,
       547.30062913, 544.34762569, 540.39867018, 535.54244764,
       529.88801835, 523.56236859, 516.70755884, 509.47753334,
       502.03466287, 494.54609826, 487.18001652, 480.10184397,
       473.47054111, 467.43503271, 462.13086326, 457.67715298,
       454.1739226 , 451.69984713, 450.31048896, 450.03705009,
       450.88567135, 452.83729456, 455.84809045, 459.85044304,
       464.75446813, 470.45003188, 476.8092242 , 483.68923135,
       490.93554321, 498.38542322, 505.87156314, 513.22584042,
       520.28309383, 526.88483268, 532.88279615, 538.14228291,
       542.54517623, 545.99259661, 548.40712242, 549.73452862,
       549.94500454, 549.03382332, 547.02144815, 543.95307262,
       539.89760584, 534.94612484, 529.20982922, 522.81754381,
       515.91282556, 508.65073955, 501.19437658, 493.71119048,
       486.36923749, 479.33340204, 472.76169383, 466.80169925,
       461.58726693, 457.23550179, 453.84413508, 451.48932959,
       450.22396918, 450.0764711 , 451.05014786, 453.12313277,
       456.24887105, 460.35716537, 465.35575229, 471.13237432,
       477.55730099, 484.4862423 , 491.76358916, 499.22590805,
       506.70561138, 514.03472113, 521.04864131, 527.58985437,
       533.51145879, 538.68046809, 542.98079747, 546.3158708 ,
       548.61078952, 549.8140147 , 549.89852451, 548.86242103,
       546.72897292, 543.54609282, 539.38526135, 534.33992182,
       528.52338168, 522.06626788, 515.11359328, 507.82149995,
       500.3537526 , 492.87806073, 485.56231226, 478.57080312,
       472.06054756, 466.17775186, 461.05453094, 456.80594129,
       453.52739708, 451.29252734, 450.15152243, 450.13000686,
       451.22846382, 453.42222434, 456.66202129, 460.8750958 ,
       465.96683132, 471.82287843, 478.31172295, 485.28763941,
       492.59396378, 500.06661175, 507.53776376, 514.83963386,
       521.80823776, 528.28707567, 534.13064683, 539.20771725,
       543.40426687, 546.62605023, 548.80071302, 549.879417  ,
       549.83793681, 548.677204  , 546.42328614, 543.12680135,
       538.86178158, 533.72400997, 527.82886981, 521.30875322,
       514.31008798, 506.99004901, 499.51302861, 492.04694454,
       484.75946894, 477.81426282, 471.36730053, 465.56336694,
       460.53280588, 456.38859292, 453.22379814, 451.10949601,
       450.0931692 , 450.19764222, 451.42056882, 453.73448472,
       457.08742435, 461.40408791, 466.58753245, 472.52134898,
       479.07227677, 486.09319611, 493.42643228, 500.90729661,
       508.36778502, 515.64035101, 522.56166843, 528.97629943,
       534.74018521, 539.72388132, 543.8154647 , 546.9230472 ,
       548.97683923, 549.93071703, 549.76325857, 548.4782246 ,
       546.10447423, 542.69531676, 538.32731452, 533.09856342,
       527.12648995, 520.545214  , 513.50253683, 506.15662179,
       498.6724423 , 491.21807689, 483.96093455, 477.06399503,
       470.68214875, 464.95871819, 460.02223928, 455.98357469,
       452.93342412, 450.94028737, 450.048926  , 450.27935806,
       451.62640856, 454.05982562, 457.52495997, 461.94399214,
       467.2176802 , 473.2275885 , 479.83874743, 486.90268464,
       494.26075931, 501.74772496, 509.19544047, 516.43664621,
       523.30872031, 529.6573308 , 535.33990159, 540.22881437,
       544.21427471, 547.20677776, 549.13911835, 549.96790028,
       549.6745109 , 548.26553909, 545.77262733, 542.25176104,
       537.78201129, 532.46375901, 526.4164407 , 519.77586608,
       512.69116814, 505.32145392, 497.83223132, 490.39169214,
       483.16693483, 476.32021188, 470.00528592, 464.36397657,
       459.52297548, 455.5910011 , 452.65635709, 450.78494924,
       450.01880532, 450.37513129, 451.84592482, 454.39815506,
       457.97450443, 462.49465583, 467.85709641, 473.9413973 ,
       480.61091823, 487.71587614, 495.09670898, 502.58765917,
       510.02049611, 517.22829432, 524.04918217, 530.32997724,
       535.92962641, 540.72237363, 544.60058413, 547.47716167,
       549.28750451, 549.99095625, 549.57171889, 548.0392076 ,
       545.42783926, 541.7962596 , 537.22602605, 531.81977621,
       525.6989228 , 519.00092698, 511.87621131, 504.48478154,
       496.99263324, 489.56802391, 482.37769428, 475.58312364,
       469.33690341, 463.77931022, 459.03515563, 455.21098314,
       452.3926754 , 450.64352554, 450.00281569, 450.48493481,
       452.07905555, 454.74937739, 458.43593065, 463.05592331,
       468.50560029, 474.66257358, 481.38857085, 488.53254069,
       495.93404494, 503.42686178, 510.8427187 , 518.01507152,
       524.78284468, 530.99404857, 536.50919296, 541.20441958,
       544.97428376, 547.73412249, 549.42195574, 549.99987841,
       549.45491161, 547.79929411, 545.07020751, 541.32894122,
       536.659516  , 531.16679709, 524.97413911, 518.22061581,
       511.05789676, 503.64684118, 496.15388542, 488.74730509,
       481.59343604, 474.85293872, 468.6771902 , 463.20488445,
       458.55891767, 454.84362826, 452.1424536 , 450.51605627,
       450.00096163, 450.60873759, 452.32573484, 455.11339329,
       458.90910817, 463.62763589, 469.16300849, 475.39091344,
       482.17148542, 489.3524474 , 496.77253046, 504.26509553,
       511.66187575, 518.79675537, 525.5095004 , 531.64935704,
       537.07843736, 541.67481591, 545.33526794, 547.97758758,
       549.54243405, 549.99466425, 549.32412208, 547.54586646,
       544.69983318, 540.84993802, 536.08264131, 530.50500627,
       524.24229456, 517.43515317, 510.23645583, 502.80786977,
       495.316225  , 487.92976771, 480.81438183, 474.12986356,
       468.02633279, 462.64086166, 458.09439622, 454.48904031,
       451.90576243, 450.40257745, 450.01324365, 450.74650463,
       452.58589294, 455.49009987, 459.3939032 , 464.20963192,
       469.82913515, 476.12621096, 482.9594406 , 490.17536447,
       497.61192848, 505.10212342, 512.47773567, 519.57312487,
       526.22894389, 532.29571738, 537.63719867, 542.13342963,
       545.68343459, 548.2074881 , 549.64890536, 549.97531523,
       549.17938727, 547.2789963 , 544.31682099, 540.35938543,
       535.49556508, 529.83459086, 523.50359605, 516.64476114,
       509.41212079, 501.96810449, 494.47988881, 487.11564292,
       480.04075192, 473.4141026 , 467.38451522, 462.08740131,
       457.64172263, 454.14731955, 451.68266882, 450.30312117,
       450.03965829, 450.89819697, 452.8594563 , 455.8793906 ,
       459.89017867, 464.80174686, 470.50379193, 476.86825825,
       483.75221361, 491.00105923, 498.45200166, 505.93770879,
       513.29006779, 520.34396051, 526.94097174, 532.93294683,
       538.18531893, 542.58013109, 546.0186853 , 548.42375905,
       549.74133957, 549.94183683, 549.02074811, 546.99875907,
       543.92127923, 539.85742214, 534.89845328, 529.15574039,
       522.75825243, 515.84966319, 508.58512468, 501.12778277,
       493.6451133 , 486.30516088, 479.27276503, 472.70585819,
       466.75191893, 461.54465989, 457.20102488, 453.81856259,
       451.47323582, 450.21771556, 450.08019808, 451.06377173,
       453.14634757, 456.28115543, 460.39779429, 465.40381331,
       471.1867881 , 477.61684551, 484.54958032, 491.82929824,
       499.29251251, 506.77161542, 514.09864245, 521.10904436,
       527.64538265, 533.56086524, 538.72264315, 543.01479398,
       546.34092527, 548.62633928, 549.81971055, 549.89423852,
       548.84824946, 546.70523402, 543.51331972, 539.34419007,
       534.29147474, 528.4686468 , 522.00647444, 515.0500841 ,
       507.75570132, 500.2871422 , 492.8121345 , 485.49855075,
       478.51063829, 472.00533057, 466.12872277, 461.01279084,
       456.77242757, 453.50286238, 451.27752267, 450.14638475,
       450.13485156, 451.2431821 , 453.44648565, 456.69528077,
       460.91660653, 466.01566104, 471.87793055, 478.3717611 ,
       485.35131527, 492.65984733, 500.13322338, 507.60360753,
       514.90323104, 521.86816011, 528.34197746, 534.17929509,
       539.24901943, 543.43729542, 546.6500634 , 548.81517153,
       549.88399614, 549.83253374, 548.66194007, 546.39850413,
       543.09305782, 538.81983433, 533.67480106, 527.77350435,
       521.24847461, 514.24624994, 506.92408521, 499.44642045,
       491.9811879 , 484.69604057, 477.75458719, 471.31271781,
       465.51510295, 460.49194453, 456.35605187, 453.20030818,
       451.09558468, 450.08914892, 450.20360327, 451.43637734,
       453.75978567, 457.12164954, 461.44646871, 466.63711708,
       472.57702387, 479.13279158, 486.15719181, 493.49247167,
       500.97389659, 508.43344989, 515.70360608, 522.62109314,
       529.03055921, 534.78806151, 539.76429895, 543.84751596,
       546.94601229, 548.99020239, 549.93417817, 549.75673995,
       548.46187263, 546.07865612, 542.66061234, 538.28450317,
       533.0486066 , 527.07050957, 520.48446726, 513.43838798,
       506.09051147, 498.60585521, 491.15250843, 483.89785724,
       477.00482547, 470.62821573, 464.91123295, 459.98226823,
       455.9520155 , 452.91098553, 450.92747331, 450.04602425,
       450.28643378, 451.64330284, 454.08615907, 457.56014118,
       461.98723102, 467.2680057 , 473.28387041, 479.89972179,
       486.96698209, 494.32693588, 501.81429445, 509.26090788,
       516.49954128, 523.36763056, 529.71093324, 535.3869924 ,
       540.26833601, 544.2453396 , 547.22868826, 549.15138239,
       549.97024244, 549.66687857, 548.24810369, 545.74578042,
       542.21610553, 537.73834793, 532.4130684 , 526.35986123,
       519.7146684 , 512.62672662, 505.25521579, 497.76568413,
       490.3263304 , 483.10422643, 476.26156511, 469.95201785,
       464.3172835 , 459.48390604, 455.56043269, 452.63497622,
       450.77323608, 450.01702292, 450.38331967, 451.8639001 ,
       454.42551355, 458.01063172, 462.53874057, 467.90814855,
       473.99827033, 480.6723349 , 487.78045716, 495.16300401,
       502.65417936, 510.08574756, 517.29081162, 524.10756132,
       530.38290717, 535.97591843, 540.76098812, 544.63065389,
       547.49801139, 549.29866596, 549.99217877, 549.56297502,
       548.0206937 , 545.39997113, 541.75966309, 537.18152304,
       531.76836614, 525.64176023, 518.93929566, 511.81149534,
       504.41843431, 496.92614476, 489.50288737, 482.31537251,
       475.52501625, 469.28431536, 463.73342253, 458.99699884,
       455.18141416, 452.3723583 , 450.63291659, 450.00215314,
       450.49423355, 452.09810674, 454.77775319, 458.4729938 ,
       463.10084145, 468.55736465, 474.72002165, 481.45041246,
       488.59738702, 496.00043969, 503.49331386, 510.90773573,
       518.07719337, 524.84067622, 531.04629103, 536.55467308,
       541.24211598, 545.00334987, 547.75390554, 549.43201145,
       549.99998094, 549.44505866, 547.77970696, 545.04132604,
       541.29141405, 536.61418592, 531.1146821 , 524.91640961,
       518.15856827, 510.99292463, 503.58040361, 496.08747444,
       488.68241217, 481.53151851, 474.79538713, 468.62529702,
       463.1598151 , 458.52168431, 454.81506707, 452.12320601,
       450.50655452, 450.00141912, 450.61914406, 452.34585656,
       455.14277838, 458.9470967 , 463.67337472, 469.21547043,
       475.44892031, 482.2337345 , 489.41754072, 496.83900616,
       504.3314607 , 511.72663998, 518.8584642 , 525.56676798,
       531.70089726, 537.12309274, 541.71158358, 545.36332218,
       547.99629837, 549.55138116, 549.99364676, 549.31316284,
       547.52521159, 544.66994654, 540.8114908 , 536.03649697,
       530.45220109, 524.18401444, 517.37270695, 510.17124593,
       502.74136064, 495.24991031, 487.86513675, 480.75288606,
       474.07288405, 467.97514917, 462.5966234 , 458.05809683,
       454.46149498, 451.88758979, 450.3941856 , 450.01482106,
       450.75801587, 452.60707949, 455.52048594])

In [30]:
class PeriodicTrendPriceGenerator:
    def __init__(self, start=500, amplitude=50, frequency=0.15):
        self.start = start
        self.amplitude = amplitude
        self.frequency = frequency
        self.t = 0

    def generate_price(self, last_price=None):
        value = self.amplitude * np.sin(self.frequency * self.t) + self.start
        self.t += 1
        return value

# Generate 991 days of stock prices
days = 990
generator = PeriodicTrendPriceGenerator(start= 500, amplitude=50, frequency=0.15)
stock_prices = [generator.generate_price() for _ in range(days)]
stock_prices = [500] + stock_prices
stock_prices = np.array(stock_prices)
allocation = [0.5,0.5]
portfolio_value = 1000
days_df = []
optimal_allocations = []
optimal_portfolio_values = []

for day, stock_price in enumerate(stock_prices):
    print("day: ", day)
    if day == 0:
       pass
    else:
        if day == 1:
           
            pass
        old_allocation = allocation
        
        print("stock price today", stock_prices[day])
        print("stock price yesterday", stock_prices[day-1])
        portfolio_return = sum((np.array([500, stock_prices[day]]) / np.array([500, stock_prices[day-1]])-1)*np.array(old_allocation))
        new_portfolio_value = portfolio_value*(1+portfolio_return)
        portfolio_value = new_portfolio_value
        print("portfolio_value", portfolio_value)
        if (stock_prices[day] >= stock_prices[day-1]):
            allocation = [0, 1]
        else:
            allocation = [1, 0]
        print("old_allocation", old_allocation)
        print("allocation:", allocation)
        days_df.append(day)
        optimal_allocations.append(old_allocation)
        optimal_portfolio_values.append(portfolio_value)

optimal_periodic_df_exp_4 = pd.DataFrame({"day": days_df,
                                            "optimal allocation":optimal_allocations,
                                            "optimal portfolio value": optimal_portfolio_values
                                           })

day:  0
day:  1
stock price today 500.0
stock price yesterday 500.0
portfolio_value 1000.0
old_allocation [0.5, 0.5]
allocation: [0, 1]
day:  2
stock price today 507.47190662367996
stock price yesterday 500.0
portfolio_value 1014.9438132473598
old_allocation [0, 1]
allocation: [0, 1]
day:  3
stock price today 514.776010333067
stock price yesterday 507.47190662367996
portfolio_value 1029.552020666134
old_allocation [0, 1]
allocation: [0, 1]
day:  4
stock price today 521.7482767055615
stock price yesterday 514.776010333067
portfolio_value 1043.496553411123
old_allocation [0, 1]
allocation: [0, 1]
day:  5
stock price today 528.2321236697518
stock price yesterday 521.7482767055615
portfolio_value 1056.4642473395036
old_allocation [0, 1]
allocation: [0, 1]
day:  6
stock price today 534.0819380011667
stock price yesterday 528.2321236697518
portfolio_value 1068.1638760023336
old_allocation [0, 1]
allocation: [0, 1]
day:  7
stock price today 539.1663454813742
stock price yesterday 534.0819380011667
portfolio_value 1078.3326909627485
old_allocation [0, 1]
allocation: [0, 1]
day:  8
stock price today 543.3711612797008
stock price yesterday 539.1663454813742
portfolio_value 1086.7423225594018
old_allocation [0, 1]
allocation: [0, 1]
day:  9
stock price today 546.6019542983613
stock price yesterday 543.3711612797008
portfolio_value 1093.2039085967228
old_allocation [0, 1]
allocation: [0, 1]
day:  10
stock price today 548.786167891333
stock price yesterday 546.6019542983613
portfolio_value 1097.5723357826662
old_allocation [0, 1]
allocation: [0, 1]
day:  11
stock price today 549.8747493302027
stock price yesterday 548.786167891333
portfolio_value 1099.7494986604056
old_allocation [0, 1]
allocation: [0, 1]
day:  12
stock price today 549.843251422696
stock price yesterday 549.8747493302027
portfolio_value 1099.6865028453922
old_allocation [0, 1]
allocation: [1, 0]
day:  13
stock price today 548.6923815439097
stock price yesterday 549.843251422696
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  14
stock price today 546.4479857501934
stock price yesterday 548.6923815439097
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  15
stock price today 543.1604683324437
stock price yesterday 546.4479857501934
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  16
stock price today 538.9036598443961
stock price yesterday 543.1604683324437
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  17
stock price today 533.7731590275575
stock price yesterday 538.9036598443961
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  18
stock price today 527.8841858695708
stock price yesterday 533.7731590275575
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  19
stock price today 521.3689940116915
stock price yesterday 527.8841858695708
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  20
stock price today 514.3739006171272
stock price yesterday 521.3689940116915
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  21
stock price today 507.05600040299333
stock price yesterday 514.3739006171272
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  22
stock price today 499.5796376316426
stock price yesterday 507.05600040299333
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  23
stock price today 492.1127152928376
stock price yesterday 499.5796376316426
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  24
stock price today 484.82292436457857
stock price yesterday 492.1127152928376
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  25
stock price today 477.8739778352574
stock price yesterday 484.82292436457857
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  26
stock price today 471.4219340628828
stock price yesterday 477.8739778352574
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  27
stock price today 465.6116920408013
stock price yesterday 471.4219340628828
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  28
stock price today 460.57373727869026
stock price yesterday 465.6116920408013
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  29
stock price today 456.4212113793206
stock price yesterday 460.57373727869026
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  30
stock price today 453.24737112207754
stock price yesterday 456.4212113793206
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  31
stock price today 451.1234941167452
stock price yesterday 453.24737112207754
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  32
stock price today 450.09727806205603
stock price yesterday 451.1234941167452
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [1, 0]
day:  33
stock price today 450.19176955820797
stock price yesterday 450.09727806205603
portfolio_value 1099.6865028453922
old_allocation [1, 0]
allocation: [0, 1]
day:  34
stock price today 451.404846529909
stock price yesterday 450.19176955820797
portfolio_value 1102.649694229369
old_allocation [0, 1]
allocation: [0, 1]
day:  35
stock price today 453.7092658836134
stock price yesterday 451.404846529909
portfolio_value 1108.2787150856395
old_allocation [0, 1]
allocation: [0, 1]
day:  36
stock price today 457.0532753286704
stock price yesterday 453.7092658836134
portfolio_value 1116.4471497412208
old_allocation [0, 1]
allocation: [0, 1]
day:  37
stock price today 461.36177562220064
stock price yesterday 457.0532753286704
portfolio_value 1126.9715527638486
old_allocation [0, 1]
allocation: [0, 1]
day:  38
stock price today 466.5380071361869
stock price yesterday 461.36177562220064
portfolio_value 1139.6155687509015
old_allocation [0, 1]
allocation: [0, 1]
day:  39
stock price today 472.4657228701181
stock price yesterday 466.5380071361869
portfolio_value 1154.0952403621916
old_allocation [0, 1]
allocation: [0, 1]
day:  40
stock price today 479.01179910800704
stock price yesterday 472.4657228701181
portfolio_value 1170.085385389649
old_allocation [0, 1]
allocation: [0, 1]
day:  41
stock price today 486.0292250900537
stock price yesterday 479.01179910800704
portfolio_value 1187.2268996486641
old_allocation [0, 1]
allocation: [0, 1]
day:  42
stock price today 493.3604045573741
stock price yesterday 486.0292250900537
portfolio_value 1205.1348216838917
old_allocation [0, 1]
allocation: [0, 1]
day:  43
stock price today 500.8406950242175
stock price yesterday 493.3604045573741
portfolio_value 1223.4069781736098
old_allocation [0, 1]
allocation: [0, 1]
day:  44
stock price today 508.30210529324785
stock price yesterday 500.8406950242175
portfolio_value 1241.6330158754913
old_allocation [0, 1]
allocation: [0, 1]
day:  45
stock price today 515.5770681756688
stock price yesterday 508.30210529324785
portfolio_value 1259.403617275758
old_allocation [0, 1]
allocation: [0, 1]
day:  46
stock price today 522.5022036890309
stock price yesterday 515.5770681756688
portfolio_value 1276.3196929781036
old_allocation [0, 1]
allocation: [0, 1]
day:  47
stock price today 528.92198821941
stock price yesterday 522.5022036890309
portfolio_value 1292.001344391148
old_allocation [0, 1]
allocation: [0, 1]
day:  48
stock price today 534.6922472464881
stock price yesterday 528.92198821941
portfolio_value 1306.0963954317895
old_allocation [0, 1]
allocation: [0, 1]
day:  49
stock price today 539.6833931924576
stock price yesterday 534.6922472464881
portfolio_value 1318.288301640782
old_allocation [0, 1]
allocation: [0, 1]
day:  50
stock price today 543.7833356796441
stock price yesterday 539.6833931924576
portfolio_value 1328.3032590888622
old_allocation [0, 1]
allocation: [0, 1]
day:  51
stock price today 546.8999988387369
stock price yesterday 543.7833356796441
portfolio_value 1335.916353422713
old_allocation [0, 1]
allocation: [0, 1]
day:  52
stock price today 548.96338913431
stock price yesterday 546.8999988387369
portfolio_value 1340.9566109564537
old_allocation [0, 1]
allocation: [0, 1]
day:  53
stock price today 549.9271672687303
stock price yesterday 548.96338913431
portfolio_value 1343.3108383720273
old_allocation [0, 1]
allocation: [0, 1]
day:  54
stock price today 549.769688862881
stock price yesterday 549.9271672687303
portfolio_value 1342.926164797093
old_allocation [0, 1]
allocation: [1, 0]
day:  55
stock price today 548.4944905422543
stock price yesterday 549.769688862881
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  56
stock price today 546.130210511967
stock price yesterday 548.4944905422543
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  57
stock price today 542.729945404414
stock price yesterday 546.130210511967
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  58
stock price today 538.3700578433744
stock price yesterday 542.729945404414
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  59
stock price today 533.1484615041092
stock price yesterday 538.3700578433744
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  60
stock price today 527.1824221833044
stock price yesterday 533.1484615041092
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  61
stock price today 520.6059242620878
stock price yesterday 527.1824221833044
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  62
stock price today 513.5666617056817
stock price yesterday 520.6059242620878
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  63
stock price today 506.2227211753532
stock price yesterday 513.5666617056817
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  64
stock price today 498.7390317428171
stock price yesterday 506.2227211753532
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  65
stock price today 491.283660938851
stock price yesterday 498.7390317428171
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  66
stock price today 484.0240403188863
stock price yesterday 491.283660938851
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  67
stock price today 477.12320531123396
stock price yesterday 484.0240403188863
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  68
stock price today 470.73613379284825
stock price yesterday 477.12320531123396
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  69
stock price today 465.0062656203229
stock price yesterday 470.73613379284825
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  70
stock price today 460.06228127994996
stock price yesterday 465.0062656203229
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  71
stock price today 456.0152120014165
stock price yesterday 460.06228127994996
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  72
stock price today 452.9559462357546
stock price yesterday 456.0152120014165
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  73
stock price today 450.95318849667547
stock price yesterday 452.9559462357546
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  74
stock price today 450.05191640530916
stock price yesterday 450.95318849667547
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [1, 0]
day:  75
stock price today 450.2723705898005
stock price yesterday 450.05191640530916
portfolio_value 1342.926164797093
old_allocation [1, 0]
allocation: [0, 1]
day:  76
stock price today 451.60960012443695
stock price yesterday 450.2723705898005
portfolio_value 1346.9144186800715
old_allocation [0, 1]
allocation: [0, 1]
day:  77
stock price today 454.0335737167662
stock price yesterday 451.60960012443695
portfolio_value 1354.1438597307233
old_allocation [0, 1]
allocation: [0, 1]
day:  78
stock price today 457.48985414568165
stock price yesterday 454.0335737167662
portfolio_value 1364.4521302888008
old_allocation [0, 1]
allocation: [0, 1]
day:  79
stock price today 461.90082080404835
stock price yesterday 457.48985414568165
portfolio_value 1377.6077288208828
old_allocation [0, 1]
allocation: [0, 1]
day:  80
stock price today 467.1674128901992
stock price yesterday 461.90082080404835
portfolio_value 1393.315208945726
old_allocation [0, 1]
allocation: [0, 1]
day:  81
stock price today 473.17135409997826
stock price yesterday 467.1674128901992
portfolio_value 1411.2218145230447
old_allocation [0, 1]
allocation: [0, 1]
day:  82
stock price today 479.777808857543
stock price yesterday 473.17135409997826
portfolio_value 1430.9254017959229
old_allocation [0, 1]
allocation: [0, 1]
day:  83
stock price today 486.83841043170986
stock price yesterday 479.777808857543
portfolio_value 1451.9834706726256
old_allocation [0, 1]
allocation: [0, 1]
day:  84
stock price today 494.1945929328771
stock price yesterday 486.83841043170986
portfolio_value 1473.9231023246855
old_allocation [0, 1]
allocation: [0, 1]
day:  85
stock price today 501.68115236105683
stock price yesterday 494.1945929328771
portfolio_value 1496.2515799242362
old_allocation [0, 1]
allocation: [0, 1]
day:  86
stock price today 509.1299567315567
stock price yesterday 501.68115236105683
portfolio_value 1518.4674540017336
old_allocation [0, 1]
allocation: [0, 1]
day:  87
stock price today 516.3737219568847
stock price yesterday 509.1299567315567
portfolio_value 1540.0718039199794
old_allocation [0, 1]
allocation: [0, 1]
day:  88
stock price today 523.249768686711
stock price yesterday 516.3737219568847
portfolio_value 1560.5794425560252
old_allocation [0, 1]
allocation: [0, 1]
day:  89
stock price today 529.6036757353611
stock price yesterday 523.249768686711
portfolio_value 1579.529812557951
old_allocation [0, 1]
allocation: [0, 1]
day:  90
stock price today 535.2927480487332
stock price yesterday 529.6036757353611
portfolio_value 1596.497329470087
old_allocation [0, 1]
allocation: [0, 1]
day:  91
stock price today 540.1892213275811
stock price yesterday 535.2927480487332
portfolio_value 1611.1009394423832
old_allocation [0, 1]
allocation: [0, 1]
day:  92
stock price today 544.1831313382318
stock price yesterday 540.1892213275811
portfolio_value 1623.0126768783762
old_allocation [0, 1]
allocation: [0, 1]
day:  93
stock price today 547.1847834722053
stock price yesterday 544.1831313382318
portfolio_value 1631.9650298354363
old_allocation [0, 1]
allocation: [0, 1]
day:  94
stock price today 549.1267670937505
stock price yesterday 547.1847834722053
portfolio_value 1637.7569477662753
old_allocation [0, 1]
allocation: [0, 1]
day:  95
stock price today 549.9654694373959
stock price yesterday 549.1267670937505
portfolio_value 1640.2583566808014
old_allocation [0, 1]
allocation: [0, 1]
day:  96
stock price today 549.6820550566381
stock price yesterday 549.9654694373959
portfolio_value 1639.4130803275114
old_allocation [0, 1]
allocation: [1, 0]
day:  97
stock price today 548.2828888274639
stock price yesterday 549.6820550566381
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  98
stock price today 545.799393006957
stock price yesterday 548.2828888274639
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  99
stock price today 542.2873415571468
stock price yesterday 545.799393006957
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  100
stock price today 537.825607582062
stock price yesterday 542.2873415571468
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  101
stock price today 532.5143920078558
stock price yesterday 537.825607582062
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  102
stock price today 526.4729732860233
stock price yesterday 532.5143920078558
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  103
stock price today 519.8370286565307
stock price yesterday 526.4729732860233
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  104
stock price today 512.7555871295087
stock price yesterday 519.8370286565307
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  105
stock price today 505.3876826149722
stock price yesterday 512.7555871295087
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  106
stock price today 497.898782364058
stock price yesterday 505.3876826149722
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  107
stock price today 490.4570709312906
stock price yesterday 497.898782364058
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  108
stock price today 483.2296731120719
stock price yesterday 490.4570709312906
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  109
stock price today 476.3789006800767
stock price yesterday 483.2296731120719
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  110
stock price today 470.0586072147383
stock price yesterday 476.3789006800767
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  111
stock price today 464.4107328815438
stock price yesterday 470.0586072147383
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  112
stock price today 459.56211676192254
stock price yesterday 464.4107328815438
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  113
stock price today 455.62164832092475
stock price yesterday 459.56211676192254
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  114
stock price today 452.67782198458957
stock price yesterday 455.62164832092475
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  115
stock price today 450.79674974591785
stock price yesterday 452.67782198458957
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  116
stock price today 450.0206764320391
stock price yesterday 450.79674974591785
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [1, 0]
day:  117
stock price today 450.36703097646836
stock price yesterday 450.0206764320391
portfolio_value 1639.4130803275114
old_allocation [1, 0]
allocation: [0, 1]
day:  118
stock price today 451.8280350028337
stock price yesterday 450.36703097646836
portfolio_value 1644.7313850578585
old_allocation [0, 1]
allocation: [0, 1]
day:  119
stock price today 454.3708775104408
stock price yesterday 451.8280350028337
portfolio_value 1653.9877670340109
old_allocation [0, 1]
allocation: [0, 1]
day:  120
stock price today 457.9384517386119
stock price yesterday 454.3708775104408
portfolio_value 1666.9743478723594
old_allocation [0, 1]
allocation: [0, 1]
day:  121
stock price today 462.4506376614162
stock price yesterday 457.9384517386119
portfolio_value 1683.399476964683
old_allocation [0, 1]
allocation: [0, 1]
day:  122
stock price today 467.8061013107229
stock price yesterday 462.4506376614162
portfolio_value 1702.8942813220444
old_allocation [0, 1]
allocation: [0, 1]
day:  123
stock price today 473.8845705186634
stock price yesterday 467.8061013107229
portfolio_value 1725.0209496668822
old_allocation [0, 1]
allocation: [0, 1]
day:  124
stock price today 480.5495359712292
stock price yesterday 473.8845705186634
portfolio_value 1749.2825647304376
old_allocation [0, 1]
allocation: [0, 1]
day:  125
stock price today 487.6513169131688

In [31]:
upward_run_work

,episode,day,actions,allocation_weights,portfolio_return,reward,new_portfolio_value
0,1,1,"0.50, 0.50","1.00, 0.00",0.92%,-0.009174,"1,000.00"
1,1,2,"0.61, 0.97","0.00, 1.00",0.91%,0.009091,"1,009.09"
2,1,3,"0.87, 0.81","1.00, 0.00",0.90%,-0.009009,"1,009.09"
3,1,4,"0.29, 0.51","0.00, 1.00",0.89%,0.008929,"1,018.10"
4,1,5,"0.15, 0.89","0.00, 1.00",0.88%,0.008850,"1,027.11"
...,...,...,...,...,...,...,...
49945,51,446,"0.00, 1.00","0.00, 1.00",0.18%,0.001805,"5,045.45"
49946,51,447,"0.00, 1.00","0.00, 1.00",0.18%,0.001802,"5,054.55"
49947,51,448,"0.00, 1.00","0.00, 1.00",0.18%,0.001799,"5,063.64"
49948,51,449,"0.00, 1.00","0.00, 1.00",0.18%,0.001795,"5,072.73"
49949,51,450,"0.00, 1.00","0.00, 1.00",0.18%,0.001792,"5,081.82"

In [32]:
upward_run_work['allocation_weights']

0        1.00, 0.00
1        0.00, 1.00
2        1.00, 0.00
3        0.00, 1.00
4        0.00, 1.00
            ...
49945    0.00, 1.00
49946    0.00, 1.00
49947    0.00, 1.00
49948    0.00, 1.00
49949    0.00, 1.00
Name: allocation_weights, Length: 49950, dtype: object

In [33]:
upward_run_work

,episode,day,actions,allocation_weights,portfolio_return,reward,new_portfolio_value
0,1,1,"0.50, 0.50","1.00, 0.00",0.92%,-0.009174,"1,000.00"
1,1,2,"0.61, 0.97","0.00, 1.00",0.91%,0.009091,"1,009.09"
2,1,3,"0.87, 0.81","1.00, 0.00",0.90%,-0.009009,"1,009.09"
3,1,4,"0.29, 0.51","0.00, 1.00",0.89%,0.008929,"1,018.10"
4,1,5,"0.15, 0.89","0.00, 1.00",0.88%,0.008850,"1,027.11"
...,...,...,...,...,...,...,...
49945,51,446,"0.00, 1.00","0.00, 1.00",0.18%,0.001805,"5,045.45"
49946,51,447,"0.00, 1.00","0.00, 1.00",0.18%,0.001802,"5,054.55"
49947,51,448,"0.00, 1.00","0.00, 1.00",0.18%,0.001799,"5,063.64"
49948,51,449,"0.00, 1.00","0.00, 1.00",0.18%,0.001795,"5,072.73"
49949,51,450,"0.00, 1.00","0.00, 1.00",0.18%,0.001792,"5,081.82"

In [34]:
optimal_periodic_df_exp_4

     day optimal allocation  optimal portfolio value
0      1         [0.5, 0.5]              1000.000000
1      2             [0, 1]              1014.943813
2      3             [0, 1]              1029.552021
3      4             [0, 1]              1043.496553
4      5             [0, 1]              1056.464247
..   ...                ...                      ...
985  986             [1, 0]            105289.941146
986  987             [1, 0]            105289.941146
987  988             [1, 0]            105289.941146
988  989             [1, 0]            105289.941146
989  990             [1, 0]            105289.941146

[990 rows x 3 columns]

In [35]:
def clean_allocation_df(df):
    allocation_column = df.filter(regex = 'allocation').columns[0]
    portfolio_column = df.filter(regex = 'portfolio').columns[0]
    # Convert allocation_weights to [1, 0] or [0, 1] format
    if df[allocation_column].dtype == object:
        df[allocation_column] = df[allocation_column].apply(
        lambda x: [int(i) for i in x] if isinstance(x, (list, tuple)) else [int(float(i.strip())) for i in str(x).split(",")]
    )

    # Clean and convert new_portfolio_value to float with 2 decimals
    df[portfolio_column] = (
        df[portfolio_column]
        .astype(str)                      # ensure string for cleanup
        .str.replace(",", "", regex=False)  # remove thousand separators
        .astype(float)
        .round(2)
    )

    return df

optimal_upward_df_binary = clean_allocation_df(optimal_upward_df_binary)
optimal_periodic_df_binary = clean_allocation_df(optimal_periodic_df_binary)
optimal_downward_df_binary = clean_allocation_df(optimal_downward_df_binary)

In [36]:
optimal_upward_df_binary.head()

       day allocation_weights  new_portfolio_value
48510    1             [1, 0]              1000.00
48511    2             [0, 1]              1009.09
48512    3             [0, 1]              1018.18
48513    4             [0, 1]              1027.27
48514    5             [0, 1]              1036.36

In [37]:
import pandas as pd
import numpy as np
import glob
import os

# Define or load this beforehand
# optimal_upward_df_binary = pd.read_csv("path_to/optimal_upward_df_binary.csv")
# optimal_upward_df_binary = clean_allocation_df(optimal_upward_df_binary)

base_path = "Results/250619_hc_binary_udp"
agents = ["a2c", "ddpg", "ppo"]
regime = "upward"

# Placeholder dictionaries
result_dfs = {}
all_data = {}

# Function to compute mean L2 error
def compute_mean_l2_error(agent_allocs, opt_allocs):
    errors = np.linalg.norm(agent_allocs - opt_allocs, axis=1)
    return np.mean(errors)

# Clean the optimal dataframe before loop
optimal_upward_df_binary = clean_allocation_df(optimal_upward_df_binary)
opt_allocs_array = np.array(optimal_upward_df_binary["allocation_weights"].tolist())

for agent in agents:
    csv_pattern = os.path.join(base_path, agent, regime, "training_logs", "*.csv")
    csv_files = sorted(glob.glob(csv_pattern))
    
    dfs = []
    mean_errors = []  # Re-initialize for each agent

    for i, fpath in enumerate(csv_files, start=1):
        df = pd.read_csv(fpath)
        df = df.loc[df['episode'] == 50, ['day', 'allocation_weights', 'new_portfolio_value']]
        df = clean_allocation_df(df)

        agent_allocs_array = np.array(df["allocation_weights"].tolist())
        print(agent_allocs_array)
        print(opt_allocs_array)
        # Align both arrays by length (truncate to minimum length)
        min_len = min(len(agent_allocs_array), len(opt_allocs_array))
        print(len(agent_allocs_array))
        print(len(opt_allocs_array))
        error = compute_mean_l2_error(agent_allocs_array[:min_len], opt_allocs_array[:min_len])
        mean_errors.append(error)
        dfs.append(df)

    result_dfs[agent] = pd.DataFrame({
        "run": list(range(1, len(mean_errors) + 1)),
        "mean_allocation_error": mean_errors
    })

    all_data[agent] = pd.concat(dfs, ignore_index=True)

[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [1 0]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [1 0]
 ...
 [1 0]
 [0 1]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [0 1]]
990
990

In [38]:
optimal_periodic_df_binary

     day allocation_weights  new_portfolio_value
0      1             [1, 0]              1000.00
1      2             [0, 1]              1001.98
2      3             [0, 1]              1001.93
3      4             [1, 0]              1001.93
4      5             [1, 0]              1001.93
..   ...                ...                  ...
985  986             [1, 0]             95929.84
986  987             [1, 0]             95929.84
987  988             [1, 0]             95929.84
988  989             [0, 1]             96323.36
989  990             [0, 1]             96943.39

[990 rows x 3 columns]

In [39]:
import pandas as pd
import numpy as np
import glob
import os

base_path = "Results/250619_hc_binary_udp"
base_path_noisy = "Results/250619_hc_binary_udp_noise"
agents = ["a2c", "ddpg", "ppo"]
regimes = ["upward", "downward", "periodic", "upward_noise", "downward_noise", "periodic_noise"]

# Result containers
result_dfs = {}  # structure: result_dfs[agent][regime]
all_data = {}

# Utility function to clean 'allocation_weights'
def clean_allocation_df(df):
    df = df.copy()
    df["allocation_weights"] = df["allocation_weights"].apply(
        lambda x: [float(i) for i in str(x).strip("[]").split(",")]
    )
    return df

# Function to compute mean L2 error
def compute_mean_l2_error(agent_allocs, opt_allocs):
    errors = np.linalg.norm(agent_allocs - opt_allocs, axis=1)
    return np.mean(errors)

# You must define or load the optimal allocation DataFrames for each regime
optimal_data = {
    "upward": clean_allocation_df(optimal_upward_df_binary),
    "downward": clean_allocation_df(optimal_downward_df_binary),
    "periodic": clean_allocation_df(optimal_periodic_df_binary),
     "upward_noise": clean_allocation_df(optimal_upward_df_binary),
    "downward_noise": clean_allocation_df(optimal_downward_df_binary),
    "periodic_noise": clean_allocation_df(optimal_periodic_df_binary),
}

for agent in agents:
    result_dfs[agent] = {}
    all_data[agent] = {}
    
    for regime in regimes:
        # Prepare optimal allocations
        opt_allocs_array = np.array(optimal_data[regime]["allocation_weights"].tolist())

        # Gather CSVs
        # Select correct base path based on regime type
        current_base = base_path_noisy if "noise" in regime else base_path
        csv_pattern = os.path.join(current_base, agent, regime, "training_logs", "*.csv")

        csv_files = sorted(glob.glob(csv_pattern))
        print(csv_files)
        mean_errors = []
        dfs = []
        delta_vs = []

        for fpath in csv_files:
            df = pd.read_csv(fpath)
            df = df.loc[df['episode'] == 50, ['day', 'allocation_weights', 'new_portfolio_value']]
            df = clean_allocation_df(df)

            agent_allocs_array = np.array(df["allocation_weights"].tolist())
            min_len = min(len(agent_allocs_array), len(opt_allocs_array))
            opt_df = optimal_data[regime]

            error = compute_mean_l2_error(agent_allocs_array[:min_len], opt_allocs_array[:min_len])
            mean_errors.append(error)
            dfs.append(df)
              # Compute ∆V
            try:
                V_agent_T = float(str(df["new_portfolio_value"].iloc[-1]).replace(",", ""))
                V_opt_T = float(str(opt_df["new_portfolio_value"].iloc[min_len - 1]).replace(",", ""))
                delta_v = V_agent_T - V_opt_T
            except Exception as e:
                delta_v = np.nan  # fallback if any issue
            delta_vs.append(delta_v)

        result_dfs[agent][regime] = pd.DataFrame({
            "run": list(range(1, len(mean_errors) + 1)),
            "mean_allocation_error": mean_errors,
            "delta_V": delta_vs
        })
        all_data[agent][regime] = pd.concat(dfs, ignore_index=True)

# Example: access PPO's results on periodic regime
print(result_dfs["ppo"]["periodic"])

['Results/250619_hc_binary_udp/a2c/upward/training_logs/01.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/02.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/03.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/04.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/05.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/06.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/07.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/08.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/09.csv', 'Results/250619_hc_binary_udp/a2c/upward/training_logs/10.csv']
['Results/250619_hc_binary_udp/a2c/downward/training_logs/01.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/02.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/03.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/04.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/05.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/06.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/07.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/08.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/09.csv', 'Results/250619_hc_binary_udp/a2c/downward/training_logs/10.csv']
['Results/250619_hc_binary_udp/a2c/periodic/training_logs/01.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/02.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/03.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/04.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/05.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/06.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/07.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/08.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/09.csv', 'Results/250619_hc_binary_udp/a2c/periodic/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/a2c/upward_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/a2c/downward_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/a2c/periodic_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp/ddpg/upward/training_logs/01.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/02.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/03.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/04.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/05.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/06.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/07.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/08.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/09.csv', 'Results/250619_hc_binary_udp/ddpg/upward/training_logs/10.csv']
['Results/250619_hc_binary_udp/ddpg/downward/training_logs/01.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/02.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/03.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/04.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/05.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/06.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/07.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/08.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/09.csv', 'Results/250619_hc_binary_udp/ddpg/downward/training_logs/10.csv']
['Results/250619_hc_binary_udp/ddpg/periodic/training_logs/01.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/02.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/03.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/04.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/05.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/06.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/07.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/08.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/09.csv', 'Results/250619_hc_binary_udp/ddpg/periodic/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/ddpg/upward_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/ddpg/downward_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/ddpg/periodic_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp/ppo/upward/training_logs/01.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/02.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/03.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/04.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/05.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/06.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/07.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/08.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/09.csv', 'Results/250619_hc_binary_udp/ppo/upward/training_logs/10.csv']
['Results/250619_hc_binary_udp/ppo/downward/training_logs/01.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/02.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/03.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/04.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/05.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/06.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/07.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/08.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/09.csv', 'Results/250619_hc_binary_udp/ppo/downward/training_logs/10.csv']
['Results/250619_hc_binary_udp/ppo/periodic/training_logs/01.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/02.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/03.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/04.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/05.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/06.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/07.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/08.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/09.csv', 'Results/250619_hc_binary_udp/ppo/periodic/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/ppo/upward_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/ppo/downward_noise/training_logs/10.csv']
['Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/01.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/02.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/03.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/04.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/05.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/06.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/07.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/08.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/09.csv', 'Results/250619_hc_binary_udp_noise/ppo/periodic_noise/training_logs/10.csv']
   run  mean_allocation_error   delta_V
0    1               0.712821 -95986.43
1    2               0.721392 -96164.52
2    3               0.704250 -96004.40
3    4               0.727106 -96146.47
4    5               0.687108 -95967.09
5    6               0.198561 -41109.16
6    7               0.704250 -96032.49
7    8               0.259987 -45478.49
8    9               0.288557 -42487.14
9   10               0.702821 -96063.96

In [46]:
result_dfs['ppo']['downward_noise']

   run  mean_allocation_error  delta_V
0    1               0.451406  -408.83
1    2               0.564257     3.64
2    3               0.631396   128.05
3    4               0.282843   310.00
4    5               0.368553  -146.14
5    6               0.435692    42.19
6    7               0.269986   107.98
7    8               0.324269    34.04
8    9               0.511402  -105.38
9   10               0.402837   193.06

In [49]:
for agent in ["a2c", "ddpg", "ppo"]:
    print("\\begin{table}[ht]")
    print("  \\centering")
    print(f"  \\caption{{Expt. 3 - {agent.upper()} averaged results across 10 runs with different generators}}")
    print(f"  \\label{{tab:{agent}_results}}")

    # --- Clean Regimes Subtable ---
    print("  \\begin{subtable}[t]{0.48\\textwidth}")
    print("  \\centering")
    print("  \\caption{Generators with no Noise}")
    print("  \\begin{tabular}{ccc}")
    print("  \\toprule")
    print("  Regime & Mean Allocation Error & $\\Delta V$ \\\\")
    print("  \\midrule")
    for regime in ["upward", "downward", "periodic"]:
        df = result_dfs[agent].get(regime)
        if df is not None and not df.empty:
            mean_error = df["mean_allocation_error"].mean()
            delta_v = df["delta_V"].mean()
            print(f"  {regime.capitalize()} & {mean_error:.2f} & {delta_v:.2f} \\\\")
    print("  \\bottomrule")
    print("  \\end{tabular}")
    print("  \\end{subtable}")

    print("  \\hfill")

    # --- Noisy Regimes Subtable ---
    print("  \\begin{subtable}[t]{0.48\\textwidth}")
    print("  \\centering")
    print("  \\caption{Generators with Noise}")
    print("  \\begin{tabular}{ccc}")
    print("  \\toprule")
    print("  Regime & Mean Allocation Error & $\\Delta V$ \\\\")
    print("  \\midrule")
    for regime in ["upward_noise", "downward_noise", "periodic_noise"]:
        df = result_dfs[agent].get(regime)
        if df is not None and not df.empty:
            mean_error = df["mean_allocation_error"].mean()
            delta_v = df["delta_V"].mean() #np.mean(np.abs(df["delta_V"]))
            print(f"  {regime.replace('_noise','').capitalize()} & {mean_error:.2f} & {delta_v:.2f} \\\\")
    print("  \\bottomrule")
    print("  \\end{tabular}")
    print("  \\end{subtable}")

    print("\\end{table}")
    print("\n\n")

\begin{table}[ht]
  \centering
  \caption{Expt. 3 - A2C averaged results across 10 runs with different generators}
  \label{tab:a2c_results}
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with no Noise}
  \begin{tabular}{ccc}
  \toprule
  Regime & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 0.06 & -924.72 \\
  Downward & 0.01 & -70.81 \\
  Periodic & 0.47 & -75042.38 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
  \hfill
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with Noise}
  \begin{tabular}{ccc}
  \toprule
  Regime & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 0.09 & -6667.27 \\
  Downward & 0.20 & -92.60 \\
  Periodic & 0.72 & -95129.39 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
\end{table}



\begin{table}[ht]
  \centering
  \caption{Expt. 3 - DDPG averaged results across 10 runs with different generators}
  \label{tab:ddpg_results}
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with no Noise}
  \begin{tabular}{ccc}
  \toprule
  Regime & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 0.99 & -6293.64 \\
  Downward & 0.28 & -199.80 \\
  Periodic & 0.70 & -96011.37 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
  \hfill
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with Noise}
  \begin{tabular}{ccc}
  \toprule
  Regime & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 1.13 & -8475.47 \\
  Downward & 0.14 & -50.51 \\
  Periodic & 0.70 & -95962.23 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
\end{table}



\begin{table}[ht]
  \centering
  \caption{Expt. 3 - PPO averaged results across 10 runs with different generators}
  \label{tab:ppo_results}
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with no Noise}
  \begin{tabular}{ccc}
  \toprule
  Regime & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 0.04 & -572.12 \\
  Downward & 0.09 & -255.36 \\
  Periodic & 0.57 & -80144.01 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
  \hfill
  \begin{subtable}[t]{0.48\textwidth}
  \centering
  \caption{Generators with Noise}
  \begin{tabular}{ccc}
  \toprule
  Regime & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & 0.60 & -7346.26 \\
  Downward & 0.42 & 15.86 \\
  Periodic & 0.65 & -92974.54 \\
  \bottomrule
  \end{tabular}
  \end{subtable}
\end{table}

In [50]:
# Best experiments table only
# Upward no noise -> ppo
# downward no noise -> a2c
# periodic no noise -> A2C

# upward noise -> a2c
# downward noise -> ppo
# periodic noise -> ppo 

# Define which agent is best for each regime
best_agent_per_regime = {
    "upward": "ppo",
    "downward": "a2c",
    "periodic": "a2c",
    "upward_noise": "a2c",
    "downward_noise": "ppo",
    "periodic_noise": "ppo"
}

# Define the order and labels for display
regimes_order = [
    ("upward", "Upward"),
    ("downward", "Downward"),
    ("periodic", "Periodic"),
    ("upward_noise", "Upward (Noise)"),
    ("downward_noise", "Downward (Noise)"),
    ("periodic_noise", "Periodic (Noise)")
]

# Start LaTeX table
print("\\begin{table}[ht]")
print("  \\centering")
print("  \\caption{Expt. 3 -- Best Agent per Generator Regime}")
print("  \\label{tab:best_agent_results}")
print("  \\begin{tabular}{lccc}")
print("  \\toprule")
print("  Generator & Best Agent & Mean Allocation Error & $\\Delta V$ \\\\")
print("  \\midrule")

# Fill in table rows
for regime_key, label in regimes_order:
    best_agent = best_agent_per_regime[regime_key]
    df = result_dfs[best_agent].get(regime_key)
    if df is not None and not df.empty:
        mean_error = df["mean_allocation_error"].mean()
        delta_v = df["delta_V"].mean()
        print(f"  {label} & {best_agent.upper()} & {mean_error:.2f} & {delta_v:.2f} \\\\")

print("  \\bottomrule")
print("  \\end{tabular}")
print("\\end{table}")

\begin{table}[ht]
  \centering
  \caption{Expt. 3 -- Best Agent per Generator Regime}
  \label{tab:best_agent_results}
  \begin{tabular}{lccc}
  \toprule
  Generator & Best Agent & Mean Allocation Error & $\Delta V$ \\
  \midrule
  Upward & PPO & 0.04 & -572.12 \\
  Downward & A2C & 0.01 & -70.81 \\
  Periodic & A2C & 0.47 & -75042.38 \\
  Upward (Noise) & A2C & 0.09 & -6667.27 \\
  Downward (Noise) & PPO & 0.42 & 15.86 \\
  Periodic (Noise) & PPO & 0.65 & -92974.54 \\
  \bottomrule
  \end{tabular}
\end{table}