In [53]:
import csv
import pandas as pd

In [54]:
# Replace with your actual .txt file path
file_path = "250602_slr_data_extraction.csv"

# Read using proper quoting to avoid splitting commas inside quoted fields
with open(file_path, newline='', encoding='utf-8') as f:
    reader = csv.reader(f, delimiter=",", quotechar='"')
    rows = list(reader)

# Use the first row as header
header = rows[0]
data = rows[1:]

# Optional: deduplicate columns if needed (e.g., "Study ID" appears twice)
# Clean header if necessary
clean_header = []
seen = set()
for col in header:
    if col in seen:
        clean_header.append(f"{col} (dup)")
    else:
        clean_header.append(col)
        seen.add(col)

# Create DataFrame
df = pd.DataFrame(data, columns=clean_header)

# Display sample
print(df.head())

  Covidence #       Study ID  \
0         496      Chen 2024
1         496      Chen 2024
2         488    Hambly 2023
3         488    Hambly 2023
4         485  Barbieri 2020

                                               Title  Reviewer Name  \
0  Portfolio Allocation with Dynamic Risk Prefere...  Mathis Jander
1  Portfolio Allocation with Dynamic Risk Prefere...      Consensus
2  Recent advances in reinforcement learning in f...  Mathis Jander
3  Recent advances in reinforcement learning in f...      Consensus
4  Discrete-Event Simulation-Based Q-Learning Alg...  Mathis Jander

  Study ID (dup)                                        Title (dup)  \
0      Chen2024b  Portfolio Allocation with Dynamic Risk Prefere...
1      Chen2024b  Portfolio Allocation with Dynamic Risk Prefere...
2     Hambly2023  Recent advances in reinforcement learning in f...
3     Hambly2023  Recent advances in reinforcement learning in f...
4  Barbieri 2020  Discrete‑Event Simulation‑Based Q‑Learning Alg...

       Journal Subject Area (Scimago classification)  \
0  Computer Science; Economics, Econometrics and ...
1  Computer Science; Economics, Econometrics and ...
2  Business, Management and Accounting; Economics...
3  Business, Management and Accounting; Economics...
4                                   Computer Science

  What is the type of study?  \
0                    Primary
1                    Primary
2                  Secondary
3                  Secondary
4                    Primary

               What are the objectives of the study?  \
0  The paper proposes a reinforcement learning (R...
1  The paper proposes a reinforcement learning (R...
2  To review recent advancements in reinforcement...
3  To review recent advancements in reinforcement...
4  Combine discrete-event simulation with RL for ...

  Which RL technique is used?  ...  \
0         Policy-based Method  ...
1         Policy-based Method  ...
2                 Other: n.a.  ...
3                 Other: n.a.  ...
4          Value-based Method  ...

                  Which evaluation metrics are used?  \
0  Sharpe ratio; Other: Sortino ratio, Cumulated ...
1  Sharpe ratio; Other: Sortino ratio, Cumulated ...
2                                        Other: n.a.
3                                        Other: n.a.
4                                                PnL

  Are results validated using statistical tests or confidence intervals?  \
0                                                 No
1                                                 No
2                                                 No
3                                                 No
4                                                 No

  Is the code or workflow made publicly available and referred to?  \
0                                                 No
1                                                 No
2                                                 No
3                                                 No
4                                                 No

  What is the implementation status? Does the study conduct a benchmark?  \
0                   Simulation-based                                 Yes
1                   Simulation-based                                 Yes
2                   Simulation-based                                  No
3                   Simulation-based                                  No
4                   Simulation-based                                  No

  What is the model benchmarked against?  \
0  Market Indexes; Algorithmic Baselines
1  Market Indexes; Algorithmic Baselines
2                            Other: n.a.
3                            Other: n.a.
4                                    n/a

  Is a standard dataset used for all models?  \
0                                        Yes
1                                        Yes
2                                        n/a
3                                        n/a
4                                        n/a

  Does study mention Transfer Learning or similar method as potential avenue for research?  \
0                                                 No
1                                                 No
2                                                Yes
3                                                Yes
4                                                 No

  Does study mention alternative generalization methods?  \
0                                                 No
1                                                 No
2                                                Yes
3                                                Yes
4                                                 No

  Does the study propose a framework to structure RL research in finance?
0                                                 No
1                                                 No
2                                                Yes
3                                                Yes
4                                                 No

[5 rows x 41 columns]

In [55]:
df

,Covidence #,Study ID,Title,Reviewer Name,Study ID (dup),Title (dup),Journal Subject Area (Scimago classification),What is the type of study?,What are the objectives of the study?,Which RL technique is used?,...,Which evaluation metrics are used?,Are results validated using statistical tests or confidence intervals?,Is the code or workflow made publicly available and referred to?,What is the implementation status?,Does the study conduct a benchmark?,What is the model benchmarked against?,Is a standard dataset used for all models?,Does study mention Transfer Learning or similar method as potential avenue for research?,Does study mention alternative generalization methods?,Does the study propose a framework to structure RL research in finance?
0,496,Chen 2024,Portfolio Allocation with Dynamic Risk Prefere...,Mathis Jander,Chen2024b,Portfolio Allocation with Dynamic Risk Prefere...,"Computer Science; Economics, Econometrics and ...",Primary,The paper proposes a reinforcement learning (R...,Policy-based Method,...,"Sharpe ratio; Other: Sortino ratio, Cumulated ...",No,No,Simulation-based,Yes,Market Indexes; Algorithmic Baselines,Yes,No,No,No
1,496,Chen 2024,Portfolio Allocation with Dynamic Risk Prefere...,Consensus,Chen2024b,Portfolio Allocation with Dynamic Risk Prefere...,"Computer Science; Economics, Econometrics and ...",Primary,The paper proposes a reinforcement learning (R...,Policy-based Method,...,"Sharpe ratio; Other: Sortino ratio, Cumulated ...",No,No,Simulation-based,Yes,Market Indexes; Algorithmic Baselines,Yes,No,No,No
2,488,Hambly 2023,Recent advances in reinforcement learning in f...,Mathis Jander,Hambly2023,Recent advances in reinforcement learning in f...,"Business, Management and Accounting; Economics...",Secondary,To review recent advancements in reinforcement...,Other: n.a.,...,Other: n.a.,No,No,Simulation-based,No,Other: n.a.,n/a,Yes,Yes,Yes
3,488,Hambly 2023,Recent advances in reinforcement learning in f...,Consensus,Hambly2023,Recent advances in reinforcement learning in f...,"Business, Management and Accounting; Economics...",Secondary,To review recent advancements in reinforcement...,Other: n.a.,...,Other: n.a.,No,No,Simulation-based,No,Other: n.a.,n/a,Yes,Yes,Yes
4,485,Barbieri 2020,Discrete-Event Simulation-Based Q-Learning Alg...,Mathis Jander,Barbieri 2020,Discrete‑Event Simulation‑Based Q‑Learning Alg...,Computer Science,Primary,Combine discrete-event simulation with RL for ...,Value-based Method,...,PnL,No,No,Simulation-based,No,n/a,n/a,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,3,Aboussalah 2020,Continuous control with Stacked Deep Dynamic R...,Consensus,Aboussalah 2020,Continuous control with Stacked Deep Dynamic R...,"Computer Science, Engineering",Primary,Develop new RL algorithm for continuous action...,Actor-Critic Method,...,Sharpe ratio; PnL; Other: Annualized return,No,No,Simulation-based,Yes,Random or Naive Strategies; Algorithmic Baselines,Yes,No,No,No
322,2,Liang 2023,Crude oil price prediction using deep reinforc...,Mathis Jander,Liang2023,Crude oil price prediction using deep reinforc...,"Economics, Econometrics and Finance; Environme...",Primary,Develop a deep reinforcement learning (DRL) al...,Actor-Critic Method,...,"Other: MAE, MSE, RMSE, MAPE",No,No,Simulation-based,Yes,Algorithmic Baselines; State of the Art Algori...,Yes,No,No,No
323,2,Liang 2023,Crude oil price prediction using deep reinforc...,Consensus,Liang2023,Crude oil price prediction using deep reinforc...,"Economics, Econometrics and Finance; Environme...",Primary,Develop a deep reinforcement learning (DRL) al...,Actor-Critic Method,...,"Other: MAE, MSE, RMSE, MAPE",No,No,Simulation-based,Yes,Algorithmic Baselines; State of the Art Algori...,Yes,No,No,No
324,1,Lu 2022,Structural break-aware pairs trading strategy ...,Mathis Jander,Lu2022,Structural break‑aware pairs trading strategy ...,"Computer Science, Mathematics",Primary,Develop a two-phase machine learning framework...,Value-based Method,...,Sharpe ratio; PnL; Max drawdown; Other: True d...,No,No,Simulation-based,Yes,State of the Art Algorithms,Yes,No,No,No
325,1,Lu 2022,Structural break-aware pairs trading strategy ...,Consensus,Lu2022,Structural break‑aware pairs trading strategy ...,"Computer Science, Mathematics",Primary,Develop a two-phase machine learning framework...,Value-based Method,...,Sharpe ratio; PnL; Max drawdown; Other: True d...,No,No,Simulation-based,Yes,State of the Art Algorithms,Yes,No,No,No

In [56]:
# get only rows where Reviewer Name is Consensus
consensus_df = df[df['Reviewer Name'] == 'Consensus']
# Display the shape of the consensus DataFrame
print(consensus_df.shape)

(163, 41)

In [57]:
# add 'Year'column
consensus_df['Year'] = consensus_df['Study ID'].str.extract(r'(\d{4})').astype(int)

# remove columns Study ID and Title(dup)
consensus_df = consensus_df.drop(columns=['Study ID', 'Title (dup)'])

# rename Study ID(dup) to Study ID
consensus_df = consensus_df.rename(columns={'Study ID (dup)': 'Study ID'})

# Display the cleaned consensus DataFrame
consensus_df.head()

C:\Users\JanderM\AppData\Local\Temp\ipykernel_32220\2879310246.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  consensus_df['Year'] = consensus_df['Study ID'].str.extract(r'(\d{4})').astype(int)

,Covidence #,Title,Reviewer Name,Study ID,Journal Subject Area (Scimago classification),What is the type of study?,What are the objectives of the study?,Which RL technique is used?,Which finance application is tested?,What are the stated key results of the study?,...,Are results validated using statistical tests or confidence intervals?,Is the code or workflow made publicly available and referred to?,What is the implementation status?,Does the study conduct a benchmark?,What is the model benchmarked against?,Is a standard dataset used for all models?,Does study mention Transfer Learning or similar method as potential avenue for research?,Does study mention alternative generalization methods?,Does the study propose a framework to structure RL research in finance?,Year
1,496,Portfolio Allocation with Dynamic Risk Prefere...,Consensus,Chen2024b,"Computer Science; Economics, Econometrics and ...",Primary,The paper proposes a reinforcement learning (R...,Policy-based Method,Portfolio Management,The RL-based portfolio outperformed both the b...,...,No,No,Simulation-based,Yes,Market Indexes; Algorithmic Baselines,Yes,No,No,No,2024
3,488,Recent advances in reinforcement learning in f...,Consensus,Hambly2023,"Business, Management and Accounting; Economics...",Secondary,To review recent advancements in reinforcement...,Other: n.a.,Other: n.a.,RL has shown significant promise in adapting t...,...,No,No,Simulation-based,No,Other: n.a.,n/a,Yes,Yes,Yes,2023
5,485,Discrete-Event Simulation-Based Q-Learning Alg...,Consensus,Barbieri 2020,Computer Science,Primary,Combine discrete-event simulation with RL for ...,Value-based Method,Portfolio Management,showcasing benefits of discrete-event simulati...,...,No,No,Simulation-based,No,n/a,n/a,No,No,No,2020
7,477,Take Bitcoin into your portfolio: a novel ense...,Consensus,Li2021,"Business, Management and Accounting; Economics...",Primary,Design a novel ensemble portfolio optimization...,Other: not defined,Portfolio Management,Extended broad commodity asset pool by includi...,...,No,No,Simulation-based,Yes,Market Indexes; Random or Naive Strategies,Yes,No,No,No,2021
9,461,Developing an investment method for securities...,Consensus,Song2024,"Computer Science, Engineering, Materials Science",Primary,Propose and empirically test an investment str...,Actor-Critic Method,Portfolio Management,Introduced analytical approach to assess risk ...,...,No,No,Simulation-based,Yes,Algorithmic Baselines; State of the Art Algori...,Yes,No,Yes,No,2024

In [58]:
# Show value counts for 'What other datasets are used in the study?'
consensus_df['What other datasets are used in the study?'].value_counts()

# Check for if string contains 'None' and ';', if yes then remove 'None' and ';' from the string
consensus_df['What other datasets are used in the study?'] = consensus_df['What other datasets are used in the study?'].apply(
    lambda x: x.replace('; None', '') if "; None" in x else x)

# Check if string contains 'Trend'and remove it
consensus_df['What other datasets are used in the study?'] = consensus_df['What other datasets are used in the study?'].apply(
    lambda x: x.replace('Trend ', '') if 'Trend' in x else x)


# Show value counts for 'What other datasets are used in the study?'
consensus_df['What other datasets are used in the study?'].value_counts()

What other datasets are used in the study?
None                                                  87
Market Data                                           49
Market Data; Fundamental Data                          6
News Data                                              3
Market Data; Social Media Data; Other: Search Data     2
Other: Economic Data                                   2
Market Data; News Data                                 2
Fundamental Data                                       1
Market Data; Other: Text comments, Image Data          1
Social Media Data; Other: Economic Data                1
Other: na                                              1
Other: n/a                                             1
Other: Sentiment Data                                  1
                                                       1
Other: n.a.                                            1
Other: Search Data                                     1
Market Data; News Data; Social Media Data              1
Social Media Data; Other: Emissions Data               1
Market Data; News Data; Other: Economic Data           1
Name: count, dtype: int64

In [59]:
# standardize versions of 'n/a' to 'N/A' in consensus_df for all columns
consensus_df = consensus_df.replace({'Other: n/a': 'Other: N/A', 'Other: na': 'Other: N/A', 'Other: n.a.': 'Other: N/A'}, regex=True)
# Show value counts for 'What other datasets are used in the study?'
consensus_df['What other datasets are used in the study?'].value_counts()

What other datasets are used in the study?
None                                                  87
Market Data                                           49
Market Data; Fundamental Data                          6
News Data                                              3
Other: N/A                                             3
Other: Economic Data                                   2
Market Data; News Data                                 2
Market Data; Social Media Data; Other: Search Data     2
Other: Search Data                                     1
Market Data; News Data; Social Media Data              1
                                                       1
Other: Sentiment Data                                  1
Fundamental Data                                       1
Social Media Data; Other: Emissions Data               1
Social Media Data; Other: Economic Data                1
Market Data; Other: Text comments, Image Data          1
Market Data; News Data; Other: Economic Data           1
Name: count, dtype: int64

In [60]:
# make lower case for 'What is the granularity of the price dataset?'
consensus_df['What is the granularity of the price dataset?'] = consensus_df['What is the granularity of the price dataset?'].str.lower()

# Remove 'Other: ' prefix from granularity_list
consensus_df['What is the granularity of the price dataset?'] = consensus_df['What is the granularity of the price dataset?'].replace({'other: ':''}, regex=True)

# standardize version of "minute"
consensus_df['What is the granularity of the price dataset?'] = consensus_df['What is the granularity of the price dataset?'].replace({'min': 'minute', 'minutes': 'minute'})

# standardize version of 'ticker' to "tick level"
consensus_df['What is the granularity of the price dataset?'] = consensus_df['What is the granularity of the price dataset?'].apply(lambda x: 'tick level' if 'tick' in x.lower() else x)

# replace 'daily' with 'day'
consensus_df['What is the granularity of the price dataset?'] = consensus_df['What is the granularity of the price dataset?'].apply(lambda x: 'day' if 'daily' in x.lower() else x)

# replace 'hourly' with 'hour'
consensus_df['What is the granularity of the price dataset?'] = consensus_df['What is the granularity of the price dataset?'].apply(lambda x: 'hour' if 'hourly' in x.lower() else x)

# show value counts for 'What is the granularity of the price dataset?'
print(consensus_df['What is the granularity of the price dataset?'].value_counts())

What is the granularity of the price dataset?
day                            108
hour                             9
minute                           8
n/a                              6
not specified                    4
real-time orderbook              4
tick level                       4
30 minute                        2
monthly                          2
500 milisecond                   2
second                           2
30 minutes                       2
15 minute                        2
minute; 5 minute, hour           1
5 minutes                        1
minute; real-time orderbook      1
3 second                         1
milisecond                       1
30 min                           1
5 minute                         1
15 minutes                       1
Name: count, dtype: int64

In [61]:
consensus_df

,Covidence #,Title,Reviewer Name,Study ID,Journal Subject Area (Scimago classification),What is the type of study?,What are the objectives of the study?,Which RL technique is used?,Which finance application is tested?,What are the stated key results of the study?,...,Are results validated using statistical tests or confidence intervals?,Is the code or workflow made publicly available and referred to?,What is the implementation status?,Does the study conduct a benchmark?,What is the model benchmarked against?,Is a standard dataset used for all models?,Does study mention Transfer Learning or similar method as potential avenue for research?,Does study mention alternative generalization methods?,Does the study propose a framework to structure RL research in finance?,Year
1,496,Portfolio Allocation with Dynamic Risk Prefere...,Consensus,Chen2024b,"Computer Science; Economics, Econometrics and ...",Primary,The paper proposes a reinforcement learning (R...,Policy-based Method,Portfolio Management,The RL-based portfolio outperformed both the b...,...,No,No,Simulation-based,Yes,Market Indexes; Algorithmic Baselines,Yes,No,No,No,2024
3,488,Recent advances in reinforcement learning in f...,Consensus,Hambly2023,"Business, Management and Accounting; Economics...",Secondary,To review recent advancements in reinforcement...,Other: N/A,Other: N/A,RL has shown significant promise in adapting t...,...,No,No,Simulation-based,No,Other: N/A,n/a,Yes,Yes,Yes,2023
5,485,Discrete-Event Simulation-Based Q-Learning Alg...,Consensus,Barbieri 2020,Computer Science,Primary,Combine discrete-event simulation with RL for ...,Value-based Method,Portfolio Management,showcasing benefits of discrete-event simulati...,...,No,No,Simulation-based,No,n/a,n/a,No,No,No,2020
7,477,Take Bitcoin into your portfolio: a novel ense...,Consensus,Li2021,"Business, Management and Accounting; Economics...",Primary,Design a novel ensemble portfolio optimization...,Other: not defined,Portfolio Management,Extended broad commodity asset pool by includi...,...,No,No,Simulation-based,Yes,Market Indexes; Random or Naive Strategies,Yes,No,No,No,2021
9,461,Developing an investment method for securities...,Consensus,Song2024,"Computer Science, Engineering, Materials Science",Primary,Propose and empirically test an investment str...,Actor-Critic Method,Portfolio Management,Introduced analytical approach to assess risk ...,...,No,No,Simulation-based,Yes,Algorithmic Baselines; State of the Art Algori...,Yes,No,Yes,No,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,5,Outperforming algorithmic trading reinforcemen...,Consensus,Felizardo2022,"Computer Science, Engineering",Primary,The study compares reinforcement learning (RL)...,Value-based Method; Policy-based Method; Actor...,Algorithmic Trading,Propose custom supervised learning approach fo...,...,No,Yes,Simulation-based,Yes,Market Indexes; State of the Art Algorithms,Yes,No,No,No,2022
319,4,Deep Reinforcement Learning Robots for Algorit...,Consensus,Park2024b,"Computer Science, Engineering, Materials Science",Primary,Build DRL-based stock trading robots using PPO...,Actor-Critic Method,Algorithmic Trading,Compared two models using single stock and mul...,...,No,No,Simulation-based,Yes,Other: Two versions of proposed model,Yes,No,No,No,2024
321,3,Continuous control with Stacked Deep Dynamic R...,Consensus,Aboussalah 2020,"Computer Science, Engineering",Primary,Develop new RL algorithm for continuous action...,Actor-Critic Method,Portfolio Management,first attempt at continuous control using recu...,...,No,No,Simulation-based,Yes,Random or Naive Strategies; Algorithmic Baselines,Yes,No,No,No,2020
323,2,Crude oil price prediction using deep reinforc...,Consensus,Liang2023,"Economics, Econometrics and Finance; Environme...",Primary,Develop a deep reinforcement learning (DRL) al...,Actor-Critic Method,Other: Commodity Price Forecasting,Introduced improved Ornstein-Uhlenbeck process...,...,No,No,Simulation-based,Yes,Algorithmic Baselines; State of the Art Algori...,Yes,No,No,No,2023
325,1,Structural break-aware pairs trading strategy ...,Consensus,Lu2022,"Computer Science, Mathematics",Primary,Develop a two-phase machine learning framework...,Value-based Method,Algorithmic Trading,First that identified need of developing pairs...,...,No,No,Simulation-based,Yes,State of the Art Algorithms,Yes,No,No,No,2022

In [62]:
# Save cleaned data to CSV or Excel
consensus_df.to_csv("cleaned_output.csv", index=False)
# consensus_df.to_excel("cleaned_output.xlsx", index=False)